const W08quiz = [
    {
        source: "BBDL Intermediate Quiz W08 Q1",
        question: "When calibrating a VFO which of the following might require adjustment:",
        options: [
            "Zener diode",
            "Light emitting diode",
            "Variable inductor",
            "Variable voltage regulator"
        ],
        correct: 2,
        explanation: "One of the disadvantages of a traditional VFO is that it needs to be calibrated. You should recall that the inductor/ capacitor combination(tuned circuit) sets the frequency so a variable inductor would allow adjustment to ensure the VFO covers the required range; ‘c’ therefore looks like a good bet. A Zener diode has no real adjustment, so not ‘a’. An LED is also fixed so no adjustments, not ‘b’. The voltage of the supply can affect the VFO frequency, if it changes but normally a regulator would ensure a steady value, so not really an option when calibrating the resonant frequency, so ‘d’ is not really an option.",
        lookup: "See page 32-33 of the Intermediate Licence textbook",
        syllabus: "3c.1"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q2",
        question: "Which of the following statements is incorrect?",
        options: [
            "A stable VFO requires a well-regulated power supply",
            "A crystal oscillator is likely to drift in frequency",
            "Rigid mechanical construction will improve VFO stability",
            "Using a buffer amplifier will prevent unwanted changes in the frequency of a VFO"
        ],
        correct: 1,
        explanation: "",
        lookup: "See page 32-33 of the Intermediate Licence textbook",
        syllabus: "3c.1 & 3c.2"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q3",
        question: "If the RF oscillator in a transmitter suffers from excessive drift, it may:",
        options: [
            "Generate unwanted harmonics",
            "Cause the received signal to suffer from chirp",
            "Result in signals being transmitted outside of the amateur bands",
            "Cause the out of lock inhibitor to activate"
        ],
        correct: 2,
        explanation: " If the oscillator drifts whilst you are operating close to a band edge it may start to transmit outside the Amateur Bands. Drift does not cause harmonics, so not ‘a’, and chirp is a CW transmission issue, unrelated to drift, so not ‘b’. ‘c’ looks good, but let’s check ‘d’; the out of lock inhibiter is not in the syllabus so most unlikely to be correct.",
        lookup: "See page 32-33 of the Intermediate Licence textbook",
        syllabus: "3c.2"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q4",
        question: "Rigid mechanical construction, screening and a regulated DC supply will help to ensure that an RF oscillator:",
        options: [
            "Can be used across a range of frequencies",
            "Self-corrects for any drift in frequency",
            "Has good frequency stability",
            "Does not generate unwanted harmonics"
        ],
        correct: 2,
        explanation: "Solid construction, effective metal screening and a stable supply voltage all help towards a drift-free RF oscillator.",
        lookup: "See page 33 of the Intermediate Licence textbook",
        syllabus: "3c.2"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q5",
        question: "In Amateur Radio, what do the initials DDS stand for?",
        options: [
            "Direct Digital Software",
            "Direct Digital Synthesiser",
            "Digital Demodulating Synthesiser",
            "Digital Demodulating Software"
        ],
        correct: 1,
        explanation: "However, DDS can refer to the process, Direct Digital Synthesis, or the circuit, Direct Digital Synthesiser; the context of the question/ answer should make it clear which is being used.",
        lookup: "See page 33 of the Intermediate Licence textbook",
        syllabus: "3c.3"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q6",
        question: "A direct digital synthesiser generates sine waves by:",
        options: [
            "relying on a look-up table of the voltage levels required to form a sine wave",
            "calculating the required voltage levels from downloaded software routines",
            "digitising the levels generated by a controlled variable frequency oscillator",
            "digitally mixing two signals and selecting either the sum or difference output"
        ],
        correct: 0,
        explanation: "A DDS literally builds up a sine wave of the required frequency; to achieve this, reference is made to a look-up table that specifies the voltage required at many points in the frequency’s sine wave. ‘b’ is close to being correct, but ‘a’ is more accurate, so the more correct answer.",
        lookup: "See page 33 of the Intermediate Licence textbook",
        syllabus: "3c.3"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q7",
        question: "What is the function of the Low Pass Filter in a transmitter?",
        options: [
            "To supress the carrier",
            "To attenuate one of the sidebands in an AM transmitter",
            "To prevent the radiation of unwanted signals",
            "To generate the RF signals that are then modulated"
        ],
        correct: 2,
        explanation: "‘a’ sounds like a function of a balanced modulator. ‘b’ is wrong as we do not attenuate sidebands in an AM transmitter. ‘c’ sounds good as we do not want to radiate any unwanted emissions. ‘d’ is the function of the oscillator, so ‘c’ it is.",
        lookup: "See page 34-35 of the Intermediate Licence textbook",
        syllabus: "3g.3"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q8",
        question: "What kind of transmitter is shown in the diagram? <br><br><img src='images/w08-q8.png' alt='test'  >",
        options: [
            "CW",
            "AM",
            "FM",
            "SSB"
        ],
        correct: 3,
        explanation: "The big giveaway in this diagram is the balanced modulator followed by a sideband filter; these do not feature in the other types of transmitter.",
        lookup: "See page 35-37 of the Intermediate Licence textbook",
        syllabus: "3b.1"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q9",
        question: "If an AM transmission has a Depth of Modulation of 10% then the audio signal will be:",
        options: [
            "Fairly quiet",
            "Quite loud",
            "Low in frequency",
            "High in frequency"
        ],
        correct: 0,
        explanation: " If the Depth of Modulation was 1.0 (or 100%) the carrier would be said to be fully modulated. Any further increase in modulation would result in distortion of the signal and a wide spectrum. Similarly, if the Depth of Modulation was 0.0(or 0%) the carrier would be unmodulated and carry no information. So, a normal level would be 0.8 (or 80 %), leaving some headroom for unexpected peaks. From this we can see that a Depth of Modulation of 0.1(10 %) would produce a fairly quiet but undistorted transmission.",
        lookup: "See page 36 of the Intermediate Licence textbook",
        syllabus: "3a.2"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q10",
        question: "Which type of modulator will produce two sidebands whilst supressing the carrier?",
        options: [
            "Frequency modulator using a variable capacitance diode",
            "High level modulation via a transformer",
            "An unbalanced modulator",
            "A balanced modulator"
        ],
        correct: 3,
        explanation: "The balanced modulator mixes the audio from the microphone with the output from the RF oscillator, it produces two sidebands with the carrier suppressed. ‘a’ is talking about an FM signal and the carrier is not suppressed in FM. ‘b’ is a way of producing AM, not much used these days, but it does not suppress the carrier. ‘c’ is a phrase you are unlikely to come across, because it is not covered by the syllabus, but unbalancing a modulator allows the carrier to pass, so not that one. ‘d’ is spot on. You may question the inclusion of modulators that are not in the syllabus, but it is quite common for ‘unknown’ things to be used as wrong answers in exam questions; it is seen as a valid test to see if you know the right answer.",
        lookup: "See page 36-37 of the Intermediate Licence textbook",
        syllabus: "3e.1"
    },
    {
        source: "BBDL Intermediate Quiz W08 Q11",
        question: "The SSB filter in a transmitter attenuates:",
        options: [
            "The carrier, leaving both sidebands from the output of the modulator",
            "The carrier and one of the two sidebands generated by the balanced modulator",
            "Both sidebands leaving just the modulated carrier from the modulator",
            "One of the two sidebands from the balanced modulator"
        ],
        correct: 3,
        explanation: " The sideband filter is a band-pass filter, its purpose is to only allow one of the two sidebands, generated by the balanced modulator, to reach the power amplifier.",
        lookup: "See page 36-37 of the Intermediate Licence textbook",
        syllabus: "3e.2"
    },
]

export default W08quiz