const EXAM_SECRETS_SAMPLES = [
    {
        source: "Exam Secrets FULL [Licensing] 1C1-1",
        question: "Under normal circumstances, messages may be sent:",
        options: [
            "to any amateurs who are on the frequency or channel concerned",
            "to anybody who happens to be listening to you at the time",
            "only to a licenced amateur in person who has exchanged callsigns with you",
            "to the station of an amateur with whom communication has been established",
        ],
        correct: 3,
        explanation: "In OFW611, which is part of EX309, see Condition 6 paragraph 19, known as Clause 6-19. The licence wording is 'are only addressed to one or more amateur station(s)'. The station may include all those people there and they may reply if under supervision. Some care in reading this question is needed to pick up the significant difference between the amateur in person and those there at the station, all of whom may be the intended recipient of your transmission and may reply if supervised.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1c.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1C1-2",
        question: "Under what circumstances, if any, is it permissible to send an obscured or encrypted message?",
        options: [
            "The message contains personal details about other people",
            "When the radio is being used for the purposes of licence clause 6-5",
            "You can be heard by uninvited members of the press",
            "A member of the public has asked you to send a family welfare message",
        ],
        correct: 1,
        explanation: "Clause 6-5b is assisting a User Service. Clause 6-19b: 'Unless the Radio Equipment is being used for the purposes of clause 6-5, the Licensee must ensure that transmissions between amateur stations are not encrypted for the purpose of obscuring their meaning...'",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1c.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1C1-3",
        question: "The Wireless Telegraphy (Content of Transmission) Regulations 1988 sets out requirements covering:",
        options: [
            "sending messages of a grossly offensive or obscene or menacing character",
            "limits on the number of amateurs that can be addressed in any one transmission",
            "pretending to be a person authorised ny Ofcom in order to gain an advantage",
            "time limits of a single transmission, especially when operating through a repeater",
        ],
        correct: 0,
        explanation: "More to find out aRadiating bout the The Wireless Telegraphy (Content of Transmission) Regulations 1988",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1c.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1D1-1",
        question: "If you are operating close to the edge of a band, what is the most severe situation you are risking if your transmitter frequency is unstable?",
        options: [
            "You may cause interference to another amateur station",
            "You may radiate outside the amateur band",
            "The station you are in contact with may have to re-tune",
            "Radiation of harmonics will increase noticably",
        ],
        correct: 1,
        explanation: "Radiating outside an amateur band is a breach of licence terms. You risk being required to fix the problem before transmitting again, having a modification to your licence or, possibly, losing your licence. Willing cooperation with the OFCOM inspector is clearly the best option, and it is always possible they have suitable test equipment to help you diagnose the problem.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1d.1"
    },
    {
        source: "Exam Secrets Samples FULL [Licensing] 1D1-2",
        question: "Satellite operation involves transmitting in one band and receiving in a different band. That means you must have equipment:",
        options: [
            "able to transmit on the uplink and receive on the downlink",
            "able to transmit and receive on both the uplink and downlink",
            "able to transmit and receive on the uplink and receive on the downlink",
            "able to transmit on both the uplink and downlink and receive on the downlink",
        ],
        correct: 2,
        explanation: "Obviously you must be able to transmit on the uplink and receive on the downlink but Clause 6-2 of OFW611 requires you not to cause undue interference. Clearly if your uplink is causing problems to another terrestrial station they are likely to reply on the frequency you are transmitting on. You need to be able to hear that reply so you are aware of the problem and take suitable action.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1d.1"
    },
    {
        source: "Exam Secrets Samples FULL [Licensing] 1D1-3",
        question: "If a person authorised by Ofcom is of the opinion that an urgent situation exists then your Radio Equipment may be inspected:",
        options: [
            "at any time of the day or night",
            "at any and all reasonable times",
            "during office hours but 7 days a week",
            "at any time by appointment",
        ],
        correct: 0,
        explanation: "OFW611 Clause 7-1b says 'at any time' if the matter is urgent - interference to an emergency service or air traffic control perhaps. (8-1) then says what can be done to remedy the problem; which can be modification to your equipment, a restriction on its use, or close down the station. With a less or non-urgent problem an inspection during normal working hours is more likely. Normal inspections are at a reasonable time, but if there is a problem that requires urgent resolution then an inpsection could be at any time.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1d.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1E1-1",
        question: "When operating your radio by remote control you may:",
        options: [
            "use a radio link in amateur bands below 30MHz",
            "use an internet link to access the main station",
            "utilise encryption on an amateur link",
            "provide for general use by other amateurs",
        ],
        correct: 1,
        explanation: "(6-10) does not prescribe the link technology, but does require the link to be adequately secure so that no other person can gain control. That does not include a person at your station operating under supervision. (6-10b) requires any link in an amateur band to be above 30 MHz. (6-19b) prohibits encryption of amateur transmissions (except under specific circumstances) and that also applies to remote control links on amateur frequencies.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1e.1"
    },
    {
        source: "Exam Secrets Samples FULL [Licensing] 1E1-2",
        question: "A radio link in an amateur band used for remote control of the mains transceiver must be:",
        options: [
            "limited in power to 500mW PEP ERP",
            "encrypted to prevent misuse by others",
            "compliant with Schedule 1 to the licence",
            "capable of being monitored for interference",
        ],
        correct: 2,
        explanation: "The rules for the link are the same as for the remote main transmitter, so the answer is simply compliant with Schedule 1. (6-19b) about non-encryption applies equally to links and main transmitters.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1e.1"
    },
    {
        source: "Exam Secrets Samples FULL [Licensing] 1E1-3",
        question: "A radio link in an amateur band used for remote control of the main transceiver must be:",
        options: [
            "limited in power to 500mW PEP ERP",
            "adequately secure but not encrypted",
            "below 30MHz",
            "above 144MHz",
        ],
        correct: 1,
        explanation: "In EX309 OFW611, Clause 6-11a requires the link to be adequately secure to prevent others gaining control. This applies irrespective of the link technology. Not specific in the licence, but it should also be failsafe such that loss of the link shuts down the main transmitter.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1e.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1F1-1",
        question: "When operating temporarily in another country under CEPT T/R 61-01 the rules you must follow are those:",
        options: [
            "of the host country",
            "of the host country which are also in your UK licence",
            "in your UK licence",
            "in either your UK licence or the host country licence",
        ],
        correct: 0,
        explanation: "You must follow the host country rules exactly as if you were a resident there with their licence. The UK licence ONLY applies in the UK, Channel Islands and Isle of Man, including territorial waters, and in international waters or airspace provided you are on a UK etc registered ship or aircraft.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "7h.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1F1-2",
        question: "A UK amateur radio club plans to enter contest from the south of France using their club callsign. This idea is:",
        options: [
            "a good one, it might improve their score",
            "acceptable, provide they prefix their callsign with 'F/'",
            "acceptable, if they have all their HAREC certificates",
            "not acceptable, under recommendation CEPT T/R 61-01",
        ],
        correct: 3,
        explanation: "The CEPT Recommendation T/R 61-01 on temporary visits only applies to personal Full licences and does not extend to club licences.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "7h.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1F2-1",
        question: "The American continent is in ITU Region:",
        options: [
            "1",
            "2",
            "3",
            "4",
        ],
        correct: 1,
        explanation: "Includes Canada, USA and all countries in North and South America.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "7h.2"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1G1-1",
        question: "When carrying out an RF field assessment the table setting out the relevant tables for public exposure are identified in the:",
        options: [
            "Wireless Telegraphy Licence Conditions Booklet OFW611",
            "Guidance on EMF Compliance and Enforcement",
            "Reference levels published by the Health Security Agency",
            "RSGB EMF technical note No2 v2 October 2022",
        ],
        correct: 1,
        explanation: "Another EX309 OFW611 look it up: Condition 9 - Electromagnetic Fields (EMF) Compliance. Thus, Clause 9-1 refers to footnote 3 and the relevant tables for public exposure identified in Ofcom's Guidance on EMF Compliance and Enforcement. In reality it is easier to use the RSGB EMF Assessment spreadsheet which performs the relevant calculations and compares them with the correct table.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1g.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1G1-2",
        question: "A household consists of several family members, some of whom are licenced amateurs. Which of them are permitted to be inside the EMF exclusion zone?",
        options: [
            "only the amateur operator",
            "those with an amateur licence",
            "all resident family members",
            "personal non-resident guests",
        ],
        correct: 1,
        explanation: "Anyone who does not have an amateur licence must be protected and is regarded as 'general public'.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1g.1",
        tagged: false
    },
    {
        source: "Exam Secrets FULL [Licensing] 1H1-1",
        question: "Peak Envelope Power is that power supplied to the antenna:",
        options: [
            "at the peak of an RF cycle during normal operation",
            "averaged over 1 RF cycle at the crest of the modulation",
            "averaged over 1 audio cycle on an RMS power meter",
            "by a steady carrier before it is modulated",
        ],
        correct: 1,
        explanation: "See EX309 which contains the full text of OFW611. In Condition 10 -Interpretation - Section 1, also known as 10-1, definitions are provided, including for s) 'Peak Envelope Power (PEP) is the average power supplied to the antenna by a transmitter during one radio frequency cycle at the crest of the modulation envelope taken under normal operating conditions.' ",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1h.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1H1-2",
        question: "When operating on 5.334MHz it is necessary to:",
        options: [
            "limit the antenna height to 10 metres above ground",
            "give your callsign at no more than 10 minute intervals",
            "not exceed a radiated power of 400W EIRP",
            "be contactable by a telephone in close proximity",
        ],
        correct: 3,
        explanation: "See Table C: Full Licence Parameters which can be found in EX309. Everything from 5258.5 to 5406.5 MHz has a Secondary status and is subject to note (g), which on the next page has 9 clauses about the 5 MHz band, including double sideband, network use and a telephone in close proximity. This is so the MOD, as Primary user of the 5 MHz band, can ask you to close down if there is an interference problem.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1h.1"
    },
    {
        source: "Exam Secrets FULL [Licensing] 1H1-3",
        question: "When operating double sideband in the band 5.276 to 5.284MHz the maximum bandwidth should not exceed:",
        options: [
            "4kHz",
            "6kHz",
            "8kHz",
            "10kHz",
        ],
        correct: 1,
        explanation: "See Table C: Full Licence Parameters which can be found in EX309. Everything from 5258.5 to 5406.5 MHz has a Secondary status and is subject to note (g), which on the next page has 9 clauses about the 5 MHz band, including double sideband, network use and a telephone in close proximity.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "1h.1"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2A1-1",
        question: "A potential divider uses two 1KΩ resistors to obtain a bias voltage from the supply. The two resistors are colour coded brown, black, red, silver, indicating they are 10% tolerance. How far out might the bias voltage be?",
        options: [
            "0%",
            "5%",
            "10%",
            "20%",
        ],
        correct: 2,
        explanation: "The error in the bias voltage will still be 10%. This may be shown by calculation using limit values, say 900Ω and 1100Ω. V(out) = V(in) * 900/2000 = V(in) * 0.45 which is 10% different to 0.5 expected.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2a.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2B1-1",
        question: "Two resistors are connected in parallel, 20 kΩ and 30 kΩ. They are connected in series with an 8 kΩ resistor. The effective resistance of the combination is:",
        options: [
            "12 kΩ",
            "20 kΩ",
            "28 kΩ",
            "33 kΩ",
        ],
        correct: 1,
        explanation: "The 20 kΩ and 30 kΩ resistors in parallel have a resistance of (20 x 30)/(20 + 30) which is 12 kΩ. In series with 8 kΩ gives 20 kΩ.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2b.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2B1-2",
        question: "What current is drawn from the power supply in the circuit diagram?  <br><br><img src='images/secrets-tech-q3.png' alt='test'  >",
        options: [
            "10mA",
            "11.8mA",
            "15mA",
            "18.5mA",
        ],
        correct: 0,
        explanation: "At first glance, this circuit is neither series nor parallel and cannot be solved by the normal means. However, further inpection shows that the voltages at each end of the 2 kΩ resistor are equal, so no current will pass through it. We can simply remove it, or replace it with a piece of wire, it will make no difference.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2b.1",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2B1-2",
        question: "What current is drawn from the power supply in the circuit diagram?",
        image: "images/secrets-tech-q3.png",
        options: [
            "10mA",
            "11.8mA",
            "15mA",
            "18.5mA",
        ],
        correct: 0,
        explanation: "At first glance, this circuit is neither series nor parallel and cannot be solved by the normal means. However, further inpection shows that the voltages at each end of the 2 kΩ resistor are equal, so no current will pass through it. We can simply remove it, or replace it with a piece of wire, it will make no difference.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2b.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2B1-3",
        question: "What power is dissipated in the 1kΩ resistor in the circuit diagram?  <br><br><img src='images/secrets-tech-q4.png' alt='test'  >",
        options: [
            "14mW",
            "19mW",
            "25mW",
            "225mW",
        ],
        correct: 0,
        explanation: "See Technical Basics Q3 for how to handle the 2 kΩ resistor. Then in the left pair of resistors, it is 15V across 4 kΩ so current is 3.75 mA and power = IV or I squared * R which is 3.75/1000 * 3.7/1000 * 1000 or 14 mA. Or, voltage divide 15V across 1 and 3 giving 3.75V and power = VI = V squared / R and if time permits confirm by doing it both ways.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2b.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2B1-4",
        question: "A radio receiver is reading S9 on its scale, which the handbook says is an input of 50 µV PD RMS. In 50Ω this represents an input power of:",
        options: [
            "0.05pW",
            "50pW",
            "1nW",
            "50µW",
        ],
        correct: 1,
        explanation: "power = voltage squared / resistance",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2b.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2B1-5",
        question: "The audio signal from a computer soundcard is 100mV, and must be reduced to 10mV to connect to the transmitter. A potential divider is used with a 10 kΩ resistor connected between the soundcard output and the transmitter microphone input. The resistor between the microphone input and earth should be:",
        options: [
            "900 Ω",
            "1.0 kΩ",
            "1.1 kΩ",
            "10 kΩ",
        ],
        correct: 2,
        explanation: "The voltage divider will have resistors in the ratio 9:1 with the smallest one giving 1/10 and the larger one giving 9/10.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2b.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D1-1",
        question: "A trimmer capacitor consists of five foils connected to the body of the device and four foils loosely interleaved between them with a thin insulation to prevent contact. It is adjusted so the spacing is, on average, halved. The capacitance will:",
        options: [
            "halve",
            "reduce to about 70%",
            "increase by about 40%",
            "double",
        ],
        correct: 3,
        explanation: "The formula sheet gives the capacitance as C=kA/d where A is the area of the plates and d their separation. If d is halved the capacitance will double.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D1-2",
        question: "A 1µF and a 2µF capacitor are connected in series. The two open ends are then connected to a 30V supply charging the two capacitors. What is the voltage across the 2µF capacitor?",
        options: [
            "10V",
            "15V",
            "20V",
            "30V",
        ],
        correct: 0,
        explanation: "The relevant formula is C (Farads) = Q (Coulombs) / V (Volts). So, V = Q/C which means small C gives big V, and 20V on 1µF with 10V on 2µF. Formally 1/C = 1/1 + 1/2 so Total Capacitance is 0.667 µF. Total Charge Q = CV =30 X 0.667 = 20 µC. Then Voltage on 2µF is 20µC/2µF = 10V",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D1-3",
        question: "The energy in a capacitor is given by E = Q x V, that is the product of charge and potential difference. Given that, by how much does the energy stored in a capacitor increase if the potential difference is doubled?",
        options: [
            "doubles x2",
            "triples x3",
            "quadruples x4",
            "five times x5",
        ],
        correct: 2,
        explanation: "In this question, you are given some information that is outside the syllabus (E = Q x V). You should know that for a capacitor the charge Q = V x C. So energy E = V squared x C, hence double squared or 4 times. This increase of energy as the square of voltage has hazard and safety implications.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.1",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D2-1",
        question: "Capacitors are available with assorted dielectrics, polythene, ceramic, etc. A factor affecting the choice of dielectric is:",
        options: [
            "linearity",
            "leakage resistance",
            "phase angle",
            "operating frequency",
        ],
        correct: 3,
        explanation: "Many plastics will absorb some energy from an RF field, exampled by some plastics getting hot in a microwave oven - a good test in choosing suitable materials in power amplifier design. High power AMUs, especially with resonant circuits, can develop voltages easily into the kV range. That level of dielectric stress can cause some plastics to fail.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.2",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D2-2",
        question: "Which dielectric in a capacitor is most likely to absorb energy resulting in losses as the frequency increases?",
        options: [
            "air",
            "glass",
            "polythene",
            "mica",
        ],
        correct: 2,
        explanation: "Polythene is goodd at audio frequencies but lossy at RF.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.2",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D3-1",
        question: "Apart from the capacitance, another parameter to be considered when selecting a low value capacitor (say 0.1 µF) is:",
        options: [
            "power handling",
            "polarity",
            "breakdown voltage",
            "internal resistance",
        ],
        correct: 2,
        explanation: "A 0.1 µF capacitor won't be of electrolytic construction, so polarity is not an answer, but breakdown voltage is. Most capacitors are rated for DC and must be de-rated  for AC and particularly RF. For mains use, special capacitors, class X or Y, must be used, the choice depending on intended use and failure mechanism.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.3",
        tagged: true
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D4-1",
        question: "The current arrow shows the direction of the current in the inductor shown in the diagram. The legend shows whether the current is increasing, decreasing, alternating or steady. The '+' symbol shows which end of the coil is positive for the induced back EMF in the coil. Which one correctly shows the polarity of the induced EMF?",
        image: "images/secrets-tech-q20.png",
        options: [
            "Drawing A",
            "Drawing B",
            "Drawing C",
            "Drawing D",
        ],
        correct: 1,
        explanation: "This question requires some thought. Option C can be discounted, as the back EMF won't remain at one end with an alternating current. Option D is also out, as inductive back EMF occurs when a current changes, no back EMF for steady currents. Choice is now A or B. An inductor tries to oppose a current increase. In A it is aiding so A seems wrong. In B it is trying to keep the current going when the external drive is to reduce it. That is true, we have our answer. Note opposition to change is equaslly true for increasing or decreasing currents.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D4-2",
        question: "An old style doorbell has a coil acting as an electromagnet, pulling an iron arm across to strike the gong, but in doing so breaks the electrical circuit so the arm returns to the rest position, ready to repeat the process. In breaking the circuit, the current:",
        image: "",
        options: [
            "stops instantly",
            "stops quickly",
            "increases before falling to zero",
            "reverses direction briefy",
        ],
        correct: 1,
        explanation: "The back EMF in an inductor opposes change, in this case trying to reduce the current to zero. The magnitude of the back EMF is related to the rate of change. If the current did stop instantly, the rate of chage is infinitely high, that would generate an infinite voltage to keep the current going. In reality, the resulting sparking briefly maintains the current so the rate of change is slowed. A doorbell of the type mentioned running on 6V could easily have one or two hundred volts at the breaking contact.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D7-1",
        question: "The graph shows the flow of current through a circuit from  'switch on'. The circuit comprises a resistor and:",
        image: "images/secrets-tech-q30.png",
        options: [
            "capacitor in series",
            "inductor in series",
            "capacitor in parallel",
            "inductor in parallel",
        ],
        correct: 1,
        explanation: "Options C and D can be quickly ruled out. If the resistor was in parallel then at switch on the current would rise at least to the value of V/R, which does not happen. That would also apply to option A since the capacitor is initially discharged, the current would jump up to V/R and tail off as the capacitor charges. That leaves B as the only remaining option. The current is zero and climbing just after switch on, which strongly suggests an inductor must be in the only current path, which points to B as well.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.7"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2D7-2",
        question: "A valve receiver has a power supply producing 300V. It takes about 10 seconds to unscrew the lid, and it is considered safe if the voltage has dropped to about 100V by the time the lid is off. The smoothing capacitor is 200µF. Approximately what value should be chosen as the bleeder resistor to minimise wasted power but meets the safety requirement?",
        image: "",
        options: [
            "20kΩ",
            "50kΩ",
            "100kΩ",
            "200kΩ",
        ],
        correct: 1,
        explanation: "After one time constant, the voltage on C will have fallen to about 1/3 of its initial value. From the narrative, we can conclude tha time constant CR is 10 seconds. So 'R =10s/200µF' which comes to 50kΩ when the right units are applied.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2d.7"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2E3-1",
        question: "The drawing shows the current and voltage waveforms in an unknown component. The component is probably a:",
        image: "images/secrets-tech-q21.png",
        options: [
            "resistor",
            "capacitor",
            "inductor",
            "diode",
        ],
        correct: 1,
        explanation: "The current and voltage are in phase in a resistor, and a diode only conducts in one direction. The current is leading the voltage in the drawing so it is a capacitor. Memory aid: CIVIL.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2e.3"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2E3-2",
        question: "A 318pF capacitor has a reactance at 1MHz of:",
        image: "",
        options: [
            "500Ω",
            "1000Ω",
            "1570Ω",
            "5000Ω",
        ],
        correct: 0,
        explanation: "X(c) = 1/(2 * pi * f * C)",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2e.3"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2E4-1",
        question: "A transistor amplifier is shown in the circuit diagram. Capacitor C3 is used for:",
        image: "images/secrets-tech-q22.png",
        options: [
            "coupling",
            "decoupling",
            "buffering",
            "blocking",
        ],
        correct: 1,
        explanation: "The circuit is a common emitter amplifier. C3 decouples the emitter of the transistor, removing any signal at the emitter so the full input signal is across the base-emitter junction of the transmitter. Without the decoupling, much of the voltager gain of the circuit would be lost.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2e.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2E4-2",
        question: "What is the function of the capacitor marked C in the circuit diagram?",
        image: "images/secrets-tech-q23.png",
        options: [
            "coupling",
            "decoupling",
            "DC blocking",
            "tuning",
        ],
        correct: 2,
        explanation: "The circuit is a Colpitts LC oscillator. Without capacitor C, the DC bias voltage set up by the base potential divider woukd be shorted out by the inductor in the tuned circuit. It is there for DC blocking, it could be argued that it is also a signal coupling capacitor allowing the transistor to 'see' the tuned circuit. However, the term 'coupling' in this context is normally reserved for coupling a signal from one stage to the next, betwenn a local oscillator and a mixer, for example.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2e.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2E5-1",
        question: "What is the purpose of the inductor marked 'r.f.c.' in the circuit diagram?",
        image: "images/secrets-tech-q24.png",
        options: [
            "to resonate with the 22pF capacitor in the desired frequency band",
            "to provide a dynamic impedance load for the transistor",
            "to filter out the harmonics of the RF signal from the transistor",
            "to help minimise RF signals on the positive supply rail",
        ],
        correct: 3,
        explanation: "The r.f.c. has two purposes: to provide DC power to the transistor, and as an r.f.c. to limit the RF signal getting back on to the positive supply rail. It should have a high inductance to have a high RF reactance/impedance.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2e.5"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2E6-1",
        question: "A resistor of 400Ω and a capacitor of 0.1µF are fed from an AC source. At a certain frequency the reactance of the capacitor is 300Ω. The impedance of the circuit is:",
        options: [
            "300Ω",
            "400Ω",
            "500Ω",
            "700Ω",
        ],
        correct: 2,
        explanation: "This question uses a formula from the reference booklet (Z**2 = R**2 + X**2). Look out for 3-4-5 right angled triangle ratios to avoid  the calculator.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2e.6",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2F1-1",
        question: "An audio signal from the microphone in a voice transmitter is being sampled 7000 times per second. Limitations in the filtering in the microphone amplifier mean that a signal at 4kHz is present at the sampling point. What effect will this have?",
        options: [
            "no effect as the signal is above the Nyquist limit",
            "the signal is below the Nyquist limit so will be accurately sampled",
            "the signal will appear as an alias signal at 500Hz",
            "the signal will appear as an alias signal at 3kHz",
        ],
        correct: 3,
        explanation: "Sampling at 7000 samples per second gives an upper limit of 3500Hz. The 4kHz signal is 500Hz above the limit so will show as an alias 500Hz below the limit, that is 3kHz.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2f.1",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2F1-2",
        question: "To avoid aliases appearing in the digital representation of an analogue signal, it is normal to use:",
        options: [
            "an analogue filter to remove signals at frequencies above the sampling rate",
            "an analogue filter to remove signals at frequencies above half the sampling rate",
            "an digital filter to remove signals at frequencies above the sampling rate",
            "an digital filter to remove signals at frequencies above half the sampling rate",
        ],
        correct: 1,
        explanation: "Any signal of a frequency over half the sampling rate will form an alias and must be removed by an ordinary analogue filter prior to sampling. If such signals get past the sampling and are digitised they are indistinguishable from legitimate signals.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2f.1",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2F2-1",
        question: "The Fourier transform is used to:",
        options: [
            "sample analogue signals and produce a digital representation of them for subsequent digital processing",
            "take the digital samples in the time domain and calculate the amplitudes of the signals in the frequency domain",
            "utilise the frequency domain signals from the digital sampling to produce a panoramic display of amplitude against frequency",
            "convert the frequency domain signals to an analogue domain suitable for feeding to an audio amplifier",
        ],
        correct: 1,
        explanation: "The Fourier transform is a mathematical process of taking the digitised samples of the combined incoming signals and representing the amplitudes in frequency order.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2f.2",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2F2-2",
        question: "What is the name of the mathematical process used to take a stream of digitised samples of an analogue signal and depict it as the amplitudes of the individual frequency components of the signal?",
        options: [
            "A Fourier transform",
            "A Nyquist conversion",
            "The Shannon transform",
            "Anti-alias filtering",
        ],
        correct: 0,
        explanation: "See 2F2-1",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2G1-1",
        question: "In a transformer, the energy is transferred from the primary to the secondary by:",
        options: [
            "mutual inductance",
            "electromagnetic coupling",
            "magnetic resonance",
            "eddy current production",
        ],
        correct: 0,
        explanation: "The coupling between the primary and secondary windings of a transformer is termed mutual inductance, as opposed to self-inductance of a single coil. It is magnetic coupling, not electromagnetic, which is a reference to radio waves.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2g.1",
    },
    {
        "id": 1,
        note: "This was made with form capture using gemini canvas. That's why the key names are in quotes; there's an id; and an answer; some values are null; tagged is present.",
        "source": "Exam Secrets FULL [Technical Basics] 2G1-2",
        "question": "A valve RF amplifier requires a load impedance of 1.8kΩ, which needs to be matched to a 50Ω output. The secondary has 5 turns. How many turns are required on the primary?",
        image: null,
        "options": [
            "30",
            "36",
            "180",
            "250"
        ],
        "answer": "30",
        "correct": 0,
        "explanation": "Remember the impedance ratio is the square of the turns ratio. The Impedance ratio is 1800:50 or 36:1, and the square root of 36 is 6. So primary turns = 6 x secondary turns = 30.",
        "lookup": null,
        "syllabus": "2g.1",
        "tagged": false
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2G1-3",
        question: "When selecting a core for an intermediate frequency (IF) transformer, you should consider the:",
        options: [
            "RF screening properties of the chosen material",
            "frequency range over which it will operate",
            "matching to the impedance of the following circuit",
            "resonant frequency of the chosen material",
        ],
        correct: 1,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2g.1",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H1-1",
        question: "At 10MHz, a long wire antenna presents a capacitive reactance at its feedpoint equivalent to a capacitor of about 20pF. What inductance is required to bring the system to resonance?",
        options: [
            "12.5µH",
            "25µH",
            "40µH",
            "80µH",
        ],
        correct: 0,
        explanation: "It's the EX309 resonant frequency formula, and transposing.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.1",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H1-2",
        question: "The crystal of an old oscillator circuit for a miniature CW transmitter has been lost, but the capacitor is marked as 30pF and the coil is measured as about 4.25µH. What band is the transmitter designed for?",
        options: [
            "10m",
            "15m",
            "17m",
            "20m",
        ],
        correct: 3,
        explanation: "The resont frequency formula is on EX309. Take care with units! Try an estimate first.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.1",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H2-1",
        question: "Which drawing shows the equivalent circuit of a crystal?",
        image: "images/secrets-tech-q25.png",
        options: [
            "Drawing 1",
            "Drawing 2",
            "Drawing 3",
            "Drawing 4",
        ],
        correct: 1,
        explanation: "Drawing 2 is the equivalent of a crystal. But why?",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.2"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H2-2",
        question: "A home made crystal oscillator is found to be unstable in frequency, and adjustment of the small trimmer oscillator can cause it to stop oscillating. The circuit used has been published in a well known magazine, and is known to work. What is a reasonable next check, having inspected the circuit board and soldering?",
        options: [
            "check that the gain of the transistor is sufficient for the intended operation",
            "check whether the crystal should be mounted horizontally or vertically",
            "check the stability and adequacy of the bench power supply unit",
            "check whether the crystal is designed for series or parallel operation",
        ],
        correct: 3,
        explanation: "If the circuit expects a crystal designed for parallel resonance, but a series resonance crystal is used, then it will usually work in the 'wrong' mode,but not reliably, and not on the correct frequency.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.2",
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H4-1",
        question: "A series resonant circuit has 10V peak across it when at resonance. At that frequency, the resistance of the coil is approximately 4Ω and the Q-factor is calculated as 100. The peak voltage across the capacitor will be about:",
        image: "",
        options: [
            "40V",
            "100V",
            "400V",
            "1000V",
        ],
        correct: 3,
        explanation: "The Q-factor is the ratio of X(L) to R which means it is also the ratio of the voltage across R, which is 10V peak, to the voltage across L (and C). At resonance the voltages across L and C will be equal and in antiphase, so the supply voltage is all across R. With a Q of 100 the voltage across the inductor will be Q x the supply voltage, which comes to 1000V. This may be the case in an AMU at high transmit powers, although with the antenna radiating most of the power, the loaded-Q may be rather lower.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H4-2",
        question: "A 3.5MHz tuned circuit has a 3dB bandwidth of 35kHz. At that frequency the reactance of both the coil and the capacitor are calculated to be 2.4kΩ. The coil resistance will be about:",
        image: "",
        options: [
            "2.4Ω",
            "3.5Ω",
            "24Ω",
            "35Ω",
        ],
        correct: 2,
        explanation: "The Q-factor of this circuit is 3.5MHz/35kHz which is 100.Q is also X(L)/R (and X(C)/R since X(L) = X(C) at resonance) so if X is 2.4kΩ then R must 24Ω.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H4-3",
        question: "Some antenna matching units can have tuned circuits with a high Q-factor. A significant implication of this is that:",
        image: "",
        options: [
            "there will be a need to reduce the Q-factor for satisfactory reception of wide band signals",
            "the circulating currents and voltages in the tuned circuits can be very high",
            "tuning the receiver to the wanted signal can become quite critical",
            "a low pass filter is also desirable to limit harmonic radiation",
        ],
        correct: 1,
        explanation: "Robust construction and wide spaced capacitors are needed in high power AMUs to cope with high circulating currents and voltages",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2H5-1",
        question: "Which circuit or device possesses a property commonly called its 'dynamic resistance'?",
        image: "",
        options: [
            "The input resistance of a feeder for correct impedance matching",
            "The input resistance of the base of an RF transistor amplifier",
            "The effective resistance of a parallel tuned circuit at resonance",
            "The effective resistance of a series tuned circuit at resonance",
        ],
        correct: 2,
        explanation: "Dynamic resistance R(D) of a parallel tuned circuit.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2h.5"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I1-1",
        question: "A Zener diode is:",
        image: "",
        options: [
            "forward biased, to provide a specified reference voltage",
            "reverse biased, to provide a specified reference voltage",
            "forward biased, to provide an accurately known current",
            "reverse biased, to prevent excessive current flow",
        ],
        correct: 1,
        explanation: "The Zener diode is used reverse biased and will conduct at a set voltage, determined during manufacture. The current must be limited to prevent destruction. It is a voltage reference.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.1"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I3-1",
        question: "The drawing shows a class A amplifier using an N-channel depletion mode FET. The source and drain voltages are shown. What voltage might be expected on the gate in normal operation?",
        image: "images/secrets-tech-q26.png",
        options: [
            "3.2V",
            "5.2V",
            "9.2V",
            "16V",
        ],
        correct: 0,
        explanation: "A depletion mode FET (most are) will have a reverse biased gate so the voltage will be a bit lower than the source gate which is at 4.5V, so 3.2V fits the bill.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.3"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I4-1",
        question: "A transistor amplifier has a current gain of one, and a voltage gain of about 30. It is likely that the configuration of the device is:",
        image: "",
        options: [
            "emitter follower",
            "common emitter",
            "common base",
            "common collector",
        ],
        correct: 2,
        explanation: "In a transistor, the emitter and collector currents are almost equal, but the base current is much smaller. To have a current gain of one, the input must be on the emitter, and the output on the collector; that is a common base amplifier.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I4-2",
        question: "A sine wave signal is supplied to the base of a common emitter amplifier, which is biased in class A. Which statement correctly descibes the output signal?",
        image: "",
        options: [
            "The output is a complete smooth sinewave, larger than the input, and in phase with the input.",
            "The output is a complete smooth sinewave, larger than the input, and 180 degrees out of phase with the input.",
            "The output is a complete smooth sinewave, very slightly smaller than the input, and in phase with the input.",
            "The output is a complete smooth sinewave, very slightly smaller than the input, and 180 degrees out of phase with the input.",
        ],
        correct: 1,
        explanation: "Class A means that the biasing is such that the complete cycle of signal is faithfully amplified. All four answers say that, so strictly we do not need that information. The common emitter circuit gives both voltage gain and current gain, so the output will be larger than the input, and is also 180 degrees out of phase.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I4-3",
        question: "Which configuration of transistor amplifier exhibits a high current gain but a voltage gain of about one?",
        image: "",
        options: [
            "common emitter",
            "common gate",
            "common collector",
            "common source",
        ],
        correct: 2,
        explanation: "The output from the emitter follower tracks the input on the base, so has a gain of about one; just under one to be exact,as a small part of the input signal actually drives the transistor.The current gain is high; about the value of beta for the device.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I4-4",
        question: "An amplifier operated in class C is particularly suited to:",
        image: "",
        options: [
            "audio and low frequency signals",
            "a push-pull output stage for audio or RF",
            "radio frequencies for AM and SSB",
            "radio frequencies for CW and FM",
        ],
        correct: 3,
        explanation: "A class C amplifier amplifies less than half the waveform of the signal. Audo signals would be distorted and, with many frequencies involved could not be cleaned up with tuned circuits to remove the harmonics. A push-pull circuit, even at RF, relliea on a smooth transition from one transistor conducting to the other. Each transistor must handle at least haldf the waveform, which is class B. Class C relies on tuned circuitsto remove the harmonics and thus the distortion. The other feature of class C is that it is biased into non-conduction in the absence of a signal and relies on a strong input signal to turn on the power resistors. Consequently it is not sensitive to varying drive levels; it is highly non-linear. Modulations relying on signal magnitude, such as AM or SSB cannot be handled, so FM and SSB only.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I4-5",
        question: "Which class of biasing is least likely to cause the production of harmonics in the input signal?",
        image: "",
        options: [
            "Class A",
            "Class C",
            "Class AB",
            "Class B",
        ],
        correct: 0,
        explanation: "Class A biasing ensures every part of the waveform is amplifed correctly so is least likely to cause distortion and the product of harmonics.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2I5-1",
        question: "An oscillator is, in effect, an amplifier stage and a frequency selective feedback stage. In order  to oscillate:",
        image: "",
        options: [
            "the frequency selective stage must be set manually to the wanted frequency.",
            "the gain of the amplifier stage must be at least equal to the loss in the feedback stage.",
            "the amplifier stage must provide a 90 degree phase shift at the wanted frequency",
            "the feedback stage must provide a 90 degree phase shift at the wanted frequency",
        ],
        correct: 1,
        explanation: "There are two key requirements. The gain in the amplifier must not be less than the loss in the feedback, or any oscillation will die out. The phase of the amplifier and feedback must be such that there is no overall phase change round the loop. Either both devices have a zero degree chnage or both have 180 degree change at the wanted frequency. Note answer A may be a true statementm vut it isn't the anser to the question asked.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2i.5"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2J2-1",
        question: "The circuit diagram shows a regulated supply for 13.6V. The voltage across the Zener diode D will be about:",
        image: "images/secrets-tech-q27.png",
        options: [
            "0.7V",
            "3V",
            "6V",
            "10V",
        ],
        correct: 2,
        explanation: "Regulation is achieved by monitoring the output voltage. In this circuit by means of a potential divider with two 10kΩ resistors. The voltage fed to the base of the sense transistor will be around 6.8V, which suggests the emitter will be at just over 6V.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2j.2"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2J3-1",
        question: "The secondary of a power supply transformer for a valve receiver produces 200V RMS. A half-wave rectifier is used, feeding a smoothing capacitor. The maximum reverse voltage across the diode will be about:",
        image: "",
        options: [
            "200V",
            "300V",
            "400V",
            "600V",
        ],
        correct: 3,
        explanation: "The capacitor will charge to the peak voltage of the transformer output, or 200 x 1,414 = 283V. On negative half cycles, the voltage on the capacitor, and the transformer voltage will add to double that voltage across the diode. So, at least 566V. With real life mains voltage variations and simply playing safe, we must allow at aleast 600V for the diode. 1000V and 2000V diodes are readily available and the cost differemce is negligible, so play even safer!",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2J4-1",
        question: "The drawing shows a block diagram of a typical switched mode power supply. What item or function is associated with the blank box?",
        image: "images/secrets-tech-q28.png",
        options: [
            "mains transformer (50Hz)",
            "High frequency transformer",
            "Voltage stabilisation",
            "Smoothing and filtering",
        ],
        correct: 1,
        explanation: "The mains is rectified and may be partly smoothed then chopped at some 10s of kHz so the transformer size and weight can be substantially reduced. The box is a high frequency transformer.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2j.4"
    },
    {
        source: "Exam Secrets FULL [Technical Basics] 2J4-2",
        question: "What function is performed in the blank box in the block diagram of a typical switched mode power supply?",
        image: "images/secrets-tech-q29.png",
        options: [
            "filtering",
            "voltage transformation",
            "DC smoothing",
            "high frequency chopping",
        ],
        correct: 3,
        explanation: "The mains is rectified and may be partly smoothed then chopped at some 10s of KHz so the transformer size can be substantially reduced. The box contains the electronics to chop the rectified mains before feeding to the transformer.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "2j.4"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "An FM transmission is regarded as 'narrow band' when:",
        image: "",
        options: [
            "only speech or audio signals below 3.5kHz are transmitted",
            "the deviation is less than 50% of the peak deviation for the system",
            "the modulation index is equal to or less than unity",
            "the deviation ratio does not exceed unity",
        ],
        correct: 2,
        explanation: "The definition of narrow band is where the ratio of the deviation to the audio frequency is less than one. Some amateur transmissions can be slightly over unity, but in general terms, thay are regarded as narrow band, whiich avoids taking up too much spectrum greater than that required for reasonable sounding and effective communication.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "3a.2"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3B1-1",
        question: "The diagram shows an SSB transmitter. What is the function of the box marked '2'?",
        image: "images/secrets 3B1-1.png",
        options: [
            "modulator",
            "mixer",
            "amplifier",
            "sideband filter",
        ],
        correct: 1,
        explanation: "Boxes 2 and 4 are both mixers (HINT two inputs, one output). Box 4 is better known as the modulator where the modulation is set at a fixed 'carrier' frequency set by the crystal oscillator. That is then mixed up (or down) to the transmit frequency in box 2. Box 1 is a synthesiser allowing the final frequency to be controlled.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "3b.1"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3B1-2",
        question: "The modulator of a multi-mode transceiver operates at 4.7MHz. To produce a signal at 14.1MHz the modulator output should be:",
        image: "",
        options: [
            "fed to a frequency tripler",
            "modulated on to the 14.1MHz carrier",
            "mixed with a clean signal on 9.4MHz",
            "filtered to remove the image on 11.7MHz",
        ],
        correct: 2,
        explanation: "Mixing the modulated signal at 4.7MHz with a signal at 9.4MHz will produce outputs at 4.7MHz (which must be filtered out) and 14.1MHz. A tripler will produce the right carrier frequency, but is not suitable for SSB or AM since it will damage the audio sidebands.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "3b.1"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3C1-1",
        question: "The MOST significant effect of drift in a transmitter is that:",
        image: "",
        options: [
            "the distant receiver will have to retune periodically to maintain contact",
            "the received signal quality will be markedly impaired",
            "transmission may occur outside an amateur band",
            "interference may be caused to other amateurs",
        ],
        correct: 2,
        explanation: "The question does not say where in the band the transmission is, so it applies to any part of the band. In-band drift is a nuisance to the station contacted, annoying to amateurs on adjacent frequencies and a breach of the licence if drifting out of band. As asked, the event of most significance is out of band transmission. Note if the frequency  was stated and clearly well away from the band edge, the a question on the most likely unfortunate effect would be annoying other amateurs. Read such questions carefully to be sure of what is being asked.",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "3c.1"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "",
        image: "",
        options: [
            "",
            "",
            "",
            "",
        ],
        correct: 9,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "",
        image: "",
        options: [
            "",
            "",
            "",
            "",
        ],
        correct: 9,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "",
        image: "",
        options: [
            "",
            "",
            "",
            "",
        ],
        correct: 9,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "",
        image: "",
        options: [
            "",
            "",
            "",
            "",
        ],
        correct: 9,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "",
        image: "",
        options: [
            "",
            "",
            "",
            "",
        ],
        correct: 9,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "",
        image: "",
        options: [
            "",
            "",
            "",
            "",
        ],
        correct: 9,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
    {
        source: "Exam Secrets FULL [Transmitters Receivers] 3A2-1",
        question: "",
        image: "",
        options: [
            "",
            "",
            "",
            "",
        ],
        correct: 9,
        explanation: "",
        lookup: "See page(s) x of the Full Licence text book",
        syllabus: "0"
    },
]

export default EXAM_SECRETS_SAMPLES