const OWN_QUESTIONS = [
  {
    source: "OWN QUESTIONS Q00",
    question:
      "MathJax Test of questionDiv, optionsDiv, explanationDiv and syllabusItemsDiv<br>inline: $Q = V \\cdot C$ <br><br>display: $$ Q = V \\times C $$",
    image: "",
    options: [
      "all answers are the same: $R_D$",
      "all answers are the same: $R_D$",
      "all answers are the same: $R_D$",
      "all answers are the same: $R_D$",
    ],
    correct: 1,
    explanation: `Yes its $R_D$ again!!`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
  },
  {
    source: "OWN QUESTIONS Q01",
    question:
      "What is the fundamental property that defines an inductor's behavior in a circuit?",
    image: "",
    options: [
      "It opposes changes in voltage",
      "It opposes changes in current",
      "It stores energy in an electric field",
      "It converts AC to DC",
    ],
    correct: 1,
    explanation: `Inductors oppose changes in current due to Lenz's law and self-induced back EMF`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q02",
    question: "Where does an inductor store its energy?",
    image: "",
    options: [
      "In the electric field between its turns",
      "In the resistance of the wire",
      "In the magnetic field around and within the coil",
      "In the insulation between windings",
    ],
    correct: 2,
    explanation: `Inductors store energy in the magnetic field created by current flow through the coil`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q03",
    question:
      "According to Lenz's law, the direction of induced EMF in an inductor will:",
    image: "",
    options: [
      "Always be in the same direction as the applied voltage",
      "Always oppose the change that created it",
      "Depend on the frequency of the applied signal",
      "Be random and unpredictable",
    ],
    correct: 1,
    explanation: `Lenz's law states that induced EMF opposes the change in magnetic flux that created it`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q04",
    question:
      "In a DC circuit after all transients have settled, an ideal inductor behaves like:",
    image: "",
    options: [
      "An open circuit (infinite resistance)",
      "A short circuit (zero resistance)",
      "A capacitor",
      "A current source",
    ],
    correct: 1,
    explanation: `In DC steady state, there's no change in current, so no back EMF is generated. The inductor acts like a short circuit.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q05",
    question:
      "As frequency increases in an AC circuit, the impedance of an inductor:",
    image: "",
    options: [
      "Decreases",
      "Remains constant",
      "Increases",
      "First increases then decreases",
    ],
    correct: 2,
    explanation: `Inductive reactance XL = 2πfL, so impedance increases linearly with frequency`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q06",
    question:
      "What happens to the inductance when you increase the number of turns in a coil?",
    image: "",
    options: [
      "Inductance decreases proportionally",
      "Inductance remains the same",
      "Inductance increases proportionally to the square of the turns",
      "Inductance increases linearly with turns",
    ],
    correct: 2,
    explanation: `Inductance is proportional to N², where N is the number of turns.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q07",
    question: "Adding a ferrite core to an air-core inductor will:",
    image: "",
    options: [
      "Decrease the inductance",
      "Increase the inductance",
      "Have no effect on inductance",
      "Convert it to a capacitor",
    ],
    correct: 1,
    explanation: `Ferrite cores increase magnetic permeability, concentrating the magnetic field and increasing inductance.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q08",
    question:
      "When two inductors are connected in series (assuming no mutual coupling), the total inductance is:",
    image: "",
    options: [
      "Less than the smallest individual inductance",
      "Equal to the average of the individual inductances",
      "Equal to the sum of the individual inductances",
      "Equal to the product divided by the sum",
    ],
    correct: 2,
    explanation: `Series inductors add directly: LTotal = L1 + L2 + L3... (similar to series resistors).`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q09",
    question:
      "When two equal inductors are connected in parallel (assuming no mutual coupling), the total inductance is:",
    image: "",
    options: [
      "Twice the value of one inductor",
      "Half the value of one inductor",
      "The same as one inductor",
      "Four times the value of one inductor",
    ],
    correct: 1,
    explanation: `Parallel inductors follow the reciprocal rule: 1/LTotal = 1/L1 + 1/L2. For equal values, LTotal = L/2.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q10",
    question: "The time constant of an RL circuit determines:",
    image: "",
    options: [
      "The maximum current the circuit can handle",
      "How quickly the circuit responds to changes",
      "The power consumption of the circuit",
      "The operating frequency of the circuit",
    ],
    correct: 1,
    explanation: `Explanation: The time constant τ = L/R determines how quickly current builds up or decays in response to voltage changes.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q11",
    question: "A high-Q inductor in an RF circuit indicates:",
    image: "",
    options: [
      "High losses and poor selectivity",
      "Low losses and good selectivity",
      "High current handling capability",
      "Low inductance value",
    ],
    correct: 1,
    explanation: `High Q means low losses (XL/R ratio is high) and provides good selectivity in resonant circuits.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q12",
    question:
      "Every real inductor has a self-resonant frequency above which it behaves more like:",
    image: "",
    options: [
      "A resistor",
      "A capacitor",
      "A short circuit",
      "An open circuit",
    ],
    correct: 1,
    explanation: `Above self-resonance, parasitic capacitance between windings dominates, making the inductor appear capacitive.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
  },
  {
    source: "OWN QUESTIONS Q13",
    question: "The prefix pica - p - (as in 25pW) means:",
    image: "",
    options: ["$10^{-12}$", "$10^{-9}$", "$10^{-3}$", "$10^{-6}$"],
    correct: 0,
    explanation: `pica means $10^{-12}$`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
    tagged: true,
  },
  {
    source: "OWN QUESTIONS Q14",
    question: "The prefix micro - µ - (as in 200µV) means:",
    image: "",
    options: ["$10^{-12}$", "$10^{-9}$", "$10^{-3}$", "$10^{-6}$"],
    correct: 3,
    explanation: `micro µ means $10^{-6}$`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
    tagged: true,
  },
  {
    source: "OWN QUESTIONS Q15",
    question: "The prefix milli - m - (as in 3mA) means:",
    image: "",
    options: ["$10^{-12}$", "$10^{-9}$", "$10^{-3}$", "$10^{-6}$"],
    correct: 2,
    explanation: `milli m means $10^{-3}$`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
    tagged: true,
  },
  {
    source: "OWN QUESTIONS Q16",
    question: "The prefix nano - n - (as in 10nF) means:",
    image: "",
    options: ["$10^{-12}$", "$10^{-9}$", "$10^{-3}$", "$10^{-6}$"],
    correct: 1,
    explanation: `nano n means $10^{-9}$`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
    tagged: true,
  },
  {
    source: "OWN QUESTIONS Q17",
    question:
      "What will the charge be on a $22 \\mu F$ capacitor if it is connected to a 12V DC supply for several hours? #Q",
    image: "",
    options: [
      "$264 \\mu C$",
      "$26.4 \\mu C$",
      "$2640 \\mu C$",
      "$2.64 \\mu C$",
    ],
    correct: 0,
    explanation: `$Q = V \\cdot C$ and because several hours have passed, we have exceeded 5 time constants. There is a flashcard for this also.`,
    lookup: "See page(s) 21 of the Full Licence text book",
    syllabus: "2d.1",
    reference: "BBDL FULL COURSE - Week03A - Tutorial Video - 01:18:38",
    tagged: true,
    examStrategy: 2,
    examStrategyNotes:
      "It's that well known three letter shopping channel again.",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q18",
    question:
      "If a capacitor of 1F will store 1C of charge for an applied PD of 1V, what PD would a $10,000 \\mu F$ capacitor need to achieve the same charge? #Q",
    image: "",
    options: ["10V", "100V", "1000V", "1V"],
    correct: 1,
    explanation: `$$Q = V \\cdot C$$ From this we get V = Q/C and that becomes $\\frac{1}{10 \\times 10^{-3}} = 100V $ noting that $10,000 \\mu F$ is the same as $ 10mF $.`,
    lookup: "See page(s) 21 of the Full Licence text book",
    syllabus: "2d.1",
    examStrategy: 2,
    examStrategyNotes:
      "What's that shopping channel beginning with Q called? Enter 10mF as | 10 | EXP | - | 3 |",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q19",
    question:
      "If a 10mF capacitor is charged with a constant current of 10mA for 1 minute, what would its charge be (in Coulombs), and what would the potential difference be (in Volts)? #Q",
    image: "",
    options: ["60mC & 60V", "600mC & 60V", "600mC & 600V", "60mC & 600V"],
    correct: 1,
    explanation: `First of all: $$Q = I \\cdot t$$ so Charge is current x time (which is a bit weird as that implies charge could get very high with no limit) and $$Q = 10 \\times 10^{-3} \\times 60 = 600mC$$ then use $$Q = V \\cdot C$$ to get $$V = \\frac{Q}{C} = \\frac{600 \\times 10^{-3}}{10 \\times 10^{-3}} = 60V$$ I emailed Steve about this, and the answer is to apply the formula with the numbers and not think too deeply about it.`,
    lookup: "See page(s) 21 of the Full Licence text book",
    syllabus: "2d.1",
    examStrategy: 2,
    examStrategyNotes: " Use Q = I x t then Q = V x C",
    examCalculation: 2,
    exam_NOT: "",
  },
  {
    source: "OWN QUESTIONS Q20",
    question:
      "What is the selectivity Q for a series tuned 'acceptor' circuit, with a resonant frequency $f_0$ of 10.7MHz, an upper half power frequency (-3dB) $f_2$ of 10.706MHz, and a lower half-power point (-3dB) $f_1$ of 10.694MHz.    #Q",
    image: "images/own-q20.png",
    options: ["892", "89.2", "8.92", "0.892"],
    correct: 0,
    explanation: `$$Q = \\frac{f_0}{f_2 - f_1}$$<br> Then $Q = \\frac {10.7 \\times 10^6}{(10.706 - 10.694) \\times 10^6} = 891.7$<br><br>The bandwidth comes out to 12kHz and may be provided or need to be calculated.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2h.4",
  },
  {
    source: "OWN QUESTIONS Q21",
    question:
      "What is the selectivity Q for a series tuned circuit, an 'acceptor' circuit, with a resonant frequency $f_0$ of 10.7MHz, an upper half power frequency (upper -3dB point), $f_2$, of 10.702MHz, and a lower half-power point (lower -3dB point), $f_1$, of 10.698MHz.    #Q",
    image: "images/own-q20.png",
    options: ["2675", "26.75", "267.5", "0.2675"],
    correct: 0,
    explanation: `$$Q = \\frac{f_0}{f_2 - f_1}$$<br> Then $Q = \\frac {10.7 \\times 10^6}{(10.702 - 10.698) \\times 10^6} = 2675$<br><br>The bandwidth comes out to 4kHz and may be provided or need to be calculated. The narrower the bandwith, the higher the Q. The mode of transmission determines the bandwidth required. `,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2h.4",
  },
  {
    source: "OWN QUESTIONS Q22",
    question:
      "When the magnetic fields from one coil cuts through another coil, the coils have:",
    image: "",
    options: [
      "magnetic shielding",
      "mutual inductance",
      "linked loops",
      "become good friends",
    ],
    correct: 1,
    explanation: ``,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
  },
  {
    source: "OWN QUESTIONS Q23",
    question:
      "To induce a voltage in a coil using a permanent magnet, which one of the following is true?",
    image: "",
    options: [
      "the magnet must be near the coil",
      "the north pole of the magnet has to be used",
      "the magnet must be inside the coil",
      "the magnet or the coil must move relative to the other",
    ],
    correct: 3,
    explanation: ``,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
  },
  {
    source: "OWN QUESTIONS Q24",
    question:
      "A transformer has 1000 turns on the primary winding, and 250 turns on the secondary winding. This transformer:",
    image: "",
    options: [
      "is a step down transformer",
      "is a step up transformer",
      "an isolation transformer",
      "has a turns ratio of 1250:1",
    ],
    correct: 0,
    explanation: ``,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
  },
  {
    source: "OWN QUESTIONS Q25",
    question: "A step up transformer:",
    image: "",
    options: [
      "has more output power than input power",
      "will have more current in the secondary than in the primary",
      "is located on the highest step of a stairway",
      "will have less current in the secondary than the primary",
    ],
    correct: 3,
    explanation: ``,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
  },
  {
    source: "OWN QUESTIONS Q26",
    question: `A transmitter exhibits continuous output at the operating frequency even when no drive signal is present. Between spoken words on SSB, the transmitter doesn't go quiet. This is MOST likely to be:`,
    image: "",
    options: [
      "Parasitic oscillation caused by long component leads",
      "Self-oscillation due to insufficient feedback path isolation",
      "Normal behavior for class C amplifiers",
      "Harmonic distortion from over-modulation",
    ],
    correct: 1,
    explanation: `  
Continuous output at the operating frequency when idle is the signature of self-oscillation. The frequency tells you it's NOT parasitic (which would be at a different frequency). The cure is breaking the feedback path`,
    lookup: "See page(s) 53-54 of the Full Licence text book",
    syllabus: "3g.4",
    examStrategy: 4,
    examStrategyNotes: "Frequency and timing of occurrence point to the type.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q27",
    question: `You notice a high-frequency "buzz" on your HF transmission that gets worse with certain antenna settings. A spectrum analyzer shows signals at VHF when you're transmitting on 20m. The BEST first step would be:`,
    image: "",
    options: [
      "Increase drive power to overcome the interference",
      "Check for and shorten component leads, especially on decoupling capacitors",
      "Adjust the antenna tuner for better SWR",
      "Replace all electrolytic capacitors with ceramic types",
    ],
    correct: 1,
    explanation: `  
VHF signals when transmitting HF = parasitic oscillation. Load-dependent behavior confirms this. Long leads create stray resonances at higher frequencies. Shortening leads and improving layout reduces these resonances`,
    lookup: "See page(s) 53-54 of the Full Licence text book",
    syllabus: "3g.4",
    examStrategy: 4,
    examStrategyNotes:
      "Symptoms indicate parasitic oscillation; cure requires reducing Q of stray resonances.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q28",
    question: `Why is adding a small series resistor to a transistor's base lead often effective at stopping parasitic oscillation?`,
    image: "",
    options: [
      "It increases the DC bias voltage",
      "It provides proper impedance matching",
      "It adds loss at high frequencies, damping unwanted resonances",
      "It prevents thermal runaway",
    ],
    correct: 2,
    explanation: `  
The resistor adds loss (lowers Q) of any resonance in that part of the circuit. It doesn't stop resonances from existing, but it prevents them from building up into sustained oscillation. This is damping.`,
    lookup: "See page(s) 53-54 of the Full Licence text book",
    syllabus: "3g.4",
    examStrategy: 4,
    examStrategyNotes: "Understanding the role of resistance in lowering Q",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q29",
    question: `Which statement about parasitic oscillation is FALSE?`,
    image: "",
    options: [
      "It can occur at frequencies much higher than the wanted signal",
      "It is always at a harmonic of the wanted frequency",
      "It can be caused by stray capacitance and inductance in long leads",
      "It may only occur during part of the RF cycle",
    ],
    correct: 1,
    explanation: `  
This is the question you got wrong! Parasitic oscillations occur at UNPREDICTABLE frequencies based on stray L-C resonances. They are NOT related harmonically to the wanted frequency - that's why they're called "parasitic" (random, unwanted guests).`,
    lookup: "See page(s) 53-54 of the Full Licence text book",
    syllabus: "3g.4",
    examStrategy: 4,
    examStrategyNotes:
      "Distinguishing between harmonics (mathematically related) and random parasitic frequencies.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q30",
    question: `Self-oscillation is MOST likely to occur when:`,
    image: "",
    options: [
      "The antenna SWR is greater than 3:1",
      "Input and output circuits are tuned to the same frequency with inadequate isolation",
      "The power supply voltage drops below specified minimum",
      "Using a dummy load instead of an antenna",
    ],
    correct: 1,
    explanation: `  
Self-oscillation occurs when the amplifier can "hear" its own output at the frequency it's amplifying. Same-frequency tuning + inadequate isolation = feedback loop = oscillation. The other options might cause problems, but not self-oscillation specifically.`,
    lookup: "See page(s) 53-54 of the Full Licence text book",
    syllabus: "3g.4",
    examStrategy: 4,
    examStrategyNotes:
      "Understanding the feedback mechanism in self-oscillation",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q31",
    question: `A transformer has a turns ratio of 5:1 (primary to secondary). 
    If 50V AC is applied to the primary, 
    what voltage appears across the secondary?`,
    image: "",
    options: ["10V", "50V", "250V", "5V"],
    correct: 0,
    explanation: `The secondary has fewer turns, so it's a step-down transformer and voltage decreases.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 1,
    examStrategyNotes: "Is it voltage step up or step down?",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q32",
    question: `A transformer has 100 turns on the primary and 25 turns on the secondary. 
    If the primary current is 2A, what is the secondary current?`,
    image: "",
    options: ["0.5A", "2A", "4A", "8A"],
    correct: 3,
    explanation: `Current increases because voltage decreases (power conservation).`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 1,
    examStrategyNotes: "It's voltage step down so what happens to current?",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q33",
    question: `You need to match a 50Ω transmitter output to a 12.5Ω antenna. Which statement is correct?`,
    image: "",
    options: [
      " Use a 2:1 step-up transformer (primary to secondary)",
      "Use a 2:1 step-down transformer (primary to secondary)",
      "Use a 4:1 step-up transformer (primary to secondary)",
      "Use a 4:1 step-down transformer (primary to secondary)",
    ],
    correct: 1,
    explanation: `We're going from higher to lower impedance, so we need step-down 
    (more turns on primary than secondary). This will step down voltage and step up 
    current to the lower impedance antenna.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 2,
    examStrategyNotes: "Think it through",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q34",
    question: `A step-up transformer increases voltage by a factor of 3. Which statement about the current is correct?`,
    image: "",
    options: [
      "Current increases by a factor of 3",
      "Current decreases by a factor of 3",
      "Current increases by a factor of 9",
      "Current remains unchanged",
    ],
    correct: 1,
    explanation: `Voltage and current always scale in opposite directions.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 1,
    examStrategyNotes: "Straightforward.",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q35",
    question: `You have a beam antenna with a feedpoint impedance of 200Ω and 
    want to match it to your 50Ω coaxial feedline. 
    What turns ratio transformer (balun) do you need?`,
    image: "",
    options: [
      "2:1 (feedline to antenna)",
      "4:1 (feedline to antenna)",
      "1:2 (feedline to antenna)",
      "1:4 (feedline to antenna)",
    ],
    correct: 2,
    explanation: `We're transforming from LOW to HIGH impedance, so we need 1:2 (step up).`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 2,
    examStrategyNotes: "",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q36",
    question: `A power supply transformer delivers 12V AC at 5A to a load. If the primary is connected to 240V AC mains, what is the approximate primary current? (Assume an ideal transformer)`,
    image: "",
    options: ["0.25A", "0.5A", "2.5A", "5A"],
    correct: 0,
    explanation: `Power must be conserved. Secondary power = 12V × 5A = 60W. 
    Primary power must also be 60W. Primary current = 60W / 240V = 0.25A. 
    his is a 20:1 step-down transformer, so current steps up by the same factor (0.25A × 20 = 5A). 
    Always check: low voltage side has high current, high voltage side has low current.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 1,
    examStrategyNotes: "Still straightforward.",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q37",
    question: `A transformer with 2:1 turns ratio (primary to secondary) has a 
    100Ω resistive load connected to its secondary. 
    What impedance does the primary "see" looking into the transformer?`,
    image: "",
    options: ["50Ω", "100Ω", "200Ω", "400Ω"],
    correct: 3,
    explanation: ` The primary sees a higher impedance because it's the high-voltage, low-current side`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 2,
    examStrategyNotes: "Just keep calm",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q38",
    question: `You measure 100V and 2A on the primary of a transformer, 
    and 20V on the secondary. If this is an ideal transformer, 
    what must the secondary current be?`,
    image: "",
    options: ["0.4A", "2A", "5A", "10A"],
    correct: 3,
    explanation: ` Power on primary = 100V × 2A = 200W. 
    For an ideal transformer, secondary power must also be 200W. 
    Secondary current = 200W / 20V = 10A. 
    This is a 5:1 step-down transformer (100V to 20V), so current 
    steps up by the same factor (2A × 5 = 10A). 
    If your answer doesn't conserve power, you've made an error!`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 1,
    examStrategyNotes: "Easy peasy, but still apply the rules of thumb.",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q39",
    question: `Which of the following transformers would be suitable
    to match a folded dipole with a feedpoint impedance of 300 ohms to
    a 50 ohm transmitter?`,
    image: "",
    options: [
      "50 turns to 300 turns",
      "25 turns to 100 turns",
      "5 turns to 50 turns",
      "10 turns to 25 turns",
    ],
    correct: 3,
    explanation: `Method 1: get the turns ratio for each answer and sense check it.
    Method 2: The required impedance ratio is 6, so we need a turns ratio that is 
    the square root of 6.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 2,
    examStrategyNotes: "What's the opposite of square?",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q40",
    question: `If the weakest signal a receiver can hear is 0.2µV,
    and the strongest signal the receiver can hear without distortion is 20mV, 
    what is the dynamic range?
    `,
    image: "",
    options: ["10dB", "100dB", "200dB", "20dB"],
    correct: 1,
    explanation: `1. $\\frac{V_{out}}{V_{in}} = \\frac{20 \\times 10^{-3}}{0.2 \\times 10^{-6}} = 10^5$ <br><hr>
    2. For volts, the Dynamic Range is $20 \\cdot log \\frac{V_{out}}{V_{in}} = 20 \\times 5 = 100dB$ <br><hr>
    `,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3h.3",
    examStrategy: 3,
    examStrategyNotes: "This is volts, not watts, so check EX309.",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS Q41",
    question: `A coupling transformer is used in an Intermediate Frequency amplifier. What term is given to the thickest red line?`,
    image: "images/own-q41.png",
    options: [
      "Single tuned circuit",
      "Over Coupled",
      "Critically Coupled",
      "Under Coupled",
    ],
    correct: 1,
    explanation: `Over Coupled refers to the double peak, in which the Q selectivity is not optimum. Compare this to the next red curve which
    shows Critically Coupled, and then Undercoupled. Careful design is needed to ensure the correct coupling between the primary and secondary windings.
    Having a tuned circuit in both the primary and secondary side improves the selectivity.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3i.4",
    reference: "week08 p6 IFT coupling",
    examStrategy: 4,
    examStrategyNotes:
      "Just got to drill this one. Will try to do a flashcard for this one and also a diagram with labels.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS ALIASES Q42",
    question: `An SDR receiver has a sampling rate of 14 MHz. What is the Nyquist boundary?`,
    image: "",
    options: ["3.5 MHz", "7 MHz", "14 MHz", "28 MHz"],
    correct: 1,
    explanation: `The Nyquist boundary is always half the sampling rate. With 14 MHz sampling, the boundary is 14 ÷ 2 = 7 MHz. This boundary divides frequencies that can be captured correctly (0-7 MHz) from those that will create aliases (above 7 MHz).`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "It's the one about the Nyquist Boundary...",
    examCalculation: 0,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q43",
    question: `An SDR samples at 14 MHz. A strong unwanted signal exists at 10 MHz. What is the direct result of this situation?`,
    image: "",
    options: [
      "The signal is captured correctly",
      "An alias will be created",
      "The signal is blocked by the ADC",
      "The sampling rate increases automatically",
    ],
    correct: 1,
    explanation: `The 10 MHz signal is above the Nyquist boundary (7 MHz), which means it is being undersampled. Undersampling directly causes an alias to appear. The alias is the false signal that results from not having enough samples to correctly identify the real signal frequency.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Where is the Nyquist boundary?",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q44",
    question: `An SDR has a sampling rate of 14 MHz. A strong signal at 10 MHz reaches the ADC. At what frequency will the alias appear?`,
    image: "",
    options: ["3 MHz", "4 MHz", "7 MHz", "10 MHz"],
    correct: 1,
    explanation: `The alias frequency is calculated as |sampling rate - signal frequency| = |14 - 10| = 4 MHz. Alternatively, the signal is 3 MHz above the Nyquist boundary (10 - 7 = 3), so the alias appears 3 MHz below the boundary (7 - 3 = 4 MHz). The 10 MHz signal creates a ghost at 4 MHz.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes:
      "Use the alias frequency calculation: |sampling rate - signal frequency| and/or the Nyquist Boundary mirror...",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q45",
    question: `An SDR samples at 20 MHz. Which range of frequencies can be received without creating aliases?`,
    image: "",
    options: ["0 to 10 MHz", "0 to 20 MHz", "10 to 20 MHz", "0 to 40 MHz"],
    correct: 0,
    explanation: `The usable frequency range is from 0 to the Nyquist boundary (fs/2). With 20 MHz sampling, the boundary is 20 ÷ 2 = 10 MHz. Signals from 0-10 MHz are sampled at more than twice their frequency and are captured correctly. Signals above 10 MHz are undersampled and will create aliases.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Use the Nyquist Boundary...",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q46",
    question: `With a sampling rate of 14 MHz, a signal at 9 MHz will create an alias at what frequency?`,
    image: "",
    options: ["2 MHz", "5 MHz", "7 MHz", "9 MHz"],
    correct: 1,
    explanation: `Using the formula: alias = |sampling rate - signal frequency| = |14 - 9| = 5 MHz. The 9 MHz signal is above the Nyquist boundary (7 MHz), so it is undersampled and creates an alias at 5 MHz within the usable range. Note that there are two straightforward ways to find the alias: this one, and the one that mirrors off the Nyquist BOUNDARY.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 0,
    examStrategyNotes: "",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q47",
    question: `What is the fundamental cause of aliases in an SDR system?`,
    image: "",
    options: [
      "Sampling at too high a rate",
      "Undersampling a signal",
      "Using the wrong antenna",
      "Insufficient signal strength",
    ],
    correct: 1,
    explanation: `An alias is the direct result of undersampling. Undersampling occurs when a signal is sampled at less than twice its frequency. When this happens, the ADC doesn't have enough information to correctly identify the signal frequency and creates a false signal (alias) at a different frequency.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Drill that alias.",
    examCalculation: 0,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q48",
    question: `An SDR samples at 14 MHz (Nyquist boundary 7 MHz). What is the purpose of an anti-aliasing filter in this system?`,
    image: "",
    options: [
      "To amplify signals below 7 MHz",
      "To block signals above 7 MHz before they reach the ADC",
      "To increase the sampling rate",
      "To convert digital signals to analogue",
    ],
    correct: 1,
    explanation: `An anti-aliasing filter is a low-pass filter placed before the ADC that physically blocks all signals above the Nyquist boundary (7 MHz). This prevents signals above 7 MHz from reaching the ADC, so they cannot be undersampled and cannot create aliases. The filter keeps the 0-7 MHz usable range clean.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Drill",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q49",
    question: `An SDR sampling at 14 MHz receives a signal at 15 MHz. Where will the alias appear?`,
    image: "",
    options: ["1 MHz", "7 MHz", "13 MHz", "15 MHz"],
    correct: 0,
    explanation: `Alias frequency = |14 - 15| = |-1| = 1 MHz (we take the absolute value). The 15 MHz signal is well above the Nyquist boundary (7 MHz) and creates an alias at 1 MHz. Notice that as signals get further above the sampling rate, their aliases appear closer to 0 MHz.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 0,
    examStrategyNotes: "",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q50",
    question: `An SDR samples at 14 MHz. You want to receive a signal at 3.5 MHz. A strong unwanted signal at 10 MHz also reaches the ADC. What problem will occur?`,
    image: "",
    options: [
      "The 3.5 MHz signal cannot be received",
      "An alias from the 10 MHz signal will appear at 4 MHz and may cause interference",
      "The sampling rate will automatically increase",
      "Both signals will be received correctly",
    ],
    correct: 1,
    explanation: `The 3.5 MHz wanted signal is below the Nyquist boundary (7 MHz) and will be received correctly. However, the 10 MHz unwanted signal is above 7 MHz, so it creates an alias at |14-10| = 4 MHz. This alias at 4 MHz appears in the usable range and can cause interference. This is why anti-aliasing filters are essential.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Should have this in the bag now...",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES Q51",
    question: `To correctly sample a 10 MHz signal without creating an alias, what is the minimum sampling rate required?`,
    image: "",
    options: ["5 MHz", "10 MHz", "Greater than 20 MHz", "Greater than 40 MHz"],
    correct: 2,
    explanation: `According to the Nyquist rate, the minimum sampling rate must be greater than twice the signal frequency. For a 10 MHz signal: 2 × 10 MHz = 20 MHz minimum. If you sample at 20 MHz or below, you are undersampling the signal and will create an alias. You must sample at MORE than 20 MHz.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Now it is a matter of drilling!",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "OWN QUESTIONS ALIASES ADVANCED Q52",
    question: `An SDR samples at 14 MHz. Strong signals exist at both 10 MHz and 18 MHz. What problem will occur in the usable frequency range?`,
    image: "",
    options: [
      "Both signals create aliases at different frequencies",
      "Both signals create aliases at 4 MHz causing severe interference",
      "Only the 10 MHz signal creates an alias",
      "Neither signal creates an alias",
    ],
    correct: 1,
    explanation: `Both signals are above the Nyquist boundary (7 MHz) and will create aliases. Signal at 10 MHz: |14-10| = 4 MHz. Signal at 18 MHz: |14-18| = 4 MHz. Both aliases appear at the SAME frequency (4 MHz), causing severe interference. This demonstrates that different real frequencies can create aliases at the same location, compounding the interference problem.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Focus!",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES ADVANCED Q53",
    question: `An SDR has a 14 MHz sampling rate and a perfect anti-aliasing filter cutting off at 7 MHz. A very strong signal at 10 MHz is present. What will the receiver experience?`,
    image: "",
    options: [
      "An alias at 4 MHz will appear",
      "No alias because the filter blocks the 10 MHz signal before it reaches the ADC",
      "The receiver will automatically increase its sampling rate",
      "The 10 MHz signal will appear at 10 MHz",
    ],
    correct: 1,
    explanation: `The anti-aliasing filter is a low-pass filter that physically blocks signals above 7 MHz BEFORE they reach the ADC. Since the 10 MHz signal is blocked before sampling occurs, it never reaches the ADC and therefore cannot create an alias. This is the entire purpose of anti-aliasing filters - to prevent undersampling by removing problematic frequencies before digitization.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "The purpose of anti-aliasing is...?",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES ADVANCED Q54",
    question: `An SDR samples at 14 MHz. Signals exist at 3 MHz, 11 MHz, and 25 MHz. How many of these signals are being undersampled?`,
    image: "",
    options: [
      "None - all are sampled correctly",
      "One signal only",
      "Two signals",
      "All three signals",
    ],
    correct: 2,
    explanation: `A signal is undersampled if sampling rate < 2× signal frequency. Check each: 3 MHz needs >6 MHz (14>6 ✓ not undersampled). 11 MHz needs >22 MHz (14<22 ✗ undersampled). 25 MHz needs >50 MHz (14<50 ✗ undersampled). Two signals (11 MHz and 25 MHz) are undersampled and will create aliases. Only the 3 MHz signal is correctly sampled.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Now deal with multiple signals.",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES ADVANCED Q55",
    question: `With 14 MHz sampling, a signal at 25 MHz creates an alias. At what frequency does this alias appear, and is it within the usable range?`,
    image: "",
    options: [
      "11 MHz, outside the usable range",
      "11 MHz, within the usable range",
      "3 MHz, outside the usable range",
      "3 MHz, within the usable range",
    ],
    correct: 1,
    explanation: `The alias appears at |14-25| = |-11| = 11 MHz. However, this creates a second-order effect: the 11 MHz alias itself is above the Nyquist boundary (7 MHz). In reality, what you observe is an alias of the alias: |14-11| = 3 MHz. But the direct calculation gives 11 MHz. The key insight: 11 MHz is still being "folded" back. The correct direct answer is 11 MHz, but this is actually outside the primary usable range, indicating multiple folding. The practical alias observed would be at |14-25| mod 14 = 3 MHz.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 3,
    examStrategyNotes: "Is folding part of the syllabus or not?",
    examCalculation: 1,
    exam_NOT: false,
  },

  {
    source: "OWN QUESTIONS ALIASES ADVANCED Q56",
    question: `An SDR without an anti-aliasing filter samples at 14 MHz. You observe interference at 2 MHz. Which of the following real signal frequencies could NOT be causing this interference through aliasing?`,
    image: "",
    options: ["12 MHz", "16 MHz", "5 MHz", "28 MHz"],
    correct: 2,
    explanation: `For each option, calculate the alias: 12 MHz: |14-12| = 2 MHz ✓ could cause it. 16 MHz: |14-16| = 2 MHz ✓ could cause it. 5 MHz: This is below the Nyquist boundary (7 MHz), so it's NOT being undersampled and will NOT create an alias - it would appear at 5 MHz, not 2 MHz. 28 MHz: |14-28| = 14, then |14-14| = 0, but with folding |28-14| = 14, |14-14| = 0... actually 28 = 2×14, so it aliases to 0 Hz, not 2 MHz. The answer is 5 MHz as it's correctly sampled.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 3,
    examStrategyNotes: "Probably a bit difficult",
    examCalculation: 2,
    exam_NOT: true,
  },
  {
    source: "OWN QUESTIONS ALIASES ADVANCED Q57",
    question: `With 14 MHz sampling, a signal at 25 MHz creates an alias. At what frequency does this alias appear?`,
    image: "",
    options: ["3 MHz", "7 MHz", "11 MHz", "18 MHz"],
    correct: 2,
    explanation: `Using the alias formula: |sampling rate - signal frequency| = |14 - 25| = |-11| = 11 MHz. The 25 MHz signal is far above the Nyquist boundary (7 MHz), so it is severely undersampled. The alias appears at 11 MHz. Note that this alias frequency (11 MHz) is itself above the Nyquist boundary, which shows why anti-aliasing filters must completely block signals above the boundary - otherwise you get aliases throughout and beyond your usable range.`,
    lookup: "",
    syllabus: "2f.1",
    examStrategy: 2,
    examStrategyNotes: "Bit more complicated.",
    examCalculation: 1,
    exam_NOT: false,
  },
  // {
  //   source: "OWN QUESTIONS Q39",
  //   question: ``,
  //   image: "",
  //   options: ["", "", "", ""],
  //   correct: 9,
  //   explanation: ``,
  //   lookup: "See page(s) x of the Full Licence text book",
  //   syllabus: "2g.1",
  //   examStrategy: 0,
  //   examStrategyNotes: "",
  //   examCalculation: 0,
  //   exam_NOT: false,
  // },
]

export default OWN_QUESTIONS
