const RSGB_FULL_MOCK_3 = [
  {
    source: "RSGB Full Mock 3 Q1",
    question:
      "Which one of the following messages is subject to licence restrictions?",
    options: [
      "A message sent in a language not normally heard in your location",
      "A message which includes several Q-codes",
      "A message designed to make its meaning unintelligible",
      "A message which is a sound recording in Morse code",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1c.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q2",
    question:
      "What is the best reason for avoiding causing Undue Interference to other radio users?",
    options: [
      "It is a specific condition of the licence",
      "It is simply not the way to behave",
      "It may affect a User Service",
      "It can inconvenience or disrupt commercial activities",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1d.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q3",
    question:
      "Identify the correct statement related to remote control of an amateur transmitter:",
    options: [
      "Both ends of the link are limited to 500mW PEP ERP",
      "A telephone link can be used for control and audio",
      "An amateur radio link must be in a band below 30MHz",
      "The remote end link transmitter is limited to 500mW PEP ERP",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1e.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q4",
    question:
      "If operating in Switzerland under a reciprocal licence, operation must comply with:",
    options: [
      "the rules of the European Broadcasting Union",
      "your UK licence conditions",
      "CEPT Recommendation T/R 61-01",
      "the rules of the Swiss radio regulation authorities",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7h.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q5",
    question: "The ITU Radio Regulations:",
    options: [
      "contain the frequencies allocated to amateur radio in different parts of the world",
      "specify the power limits that should be applied to amateur licences",
      "give guidance on EMC considerations between the amateur service and other radio users",
      "publish the research on the effect of radio frequency radiation on the human body",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7h.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q6",
    question:
      "When conducting an EMF assessment, what is the purpose of considering the proportion of the time spent transmitting over any 6-minute time period?",
    options: [
      "The regulations allow averaging of transmit time to assess the overall heating effect on body tissue",
      "The peak transmitted power should not exceed the limit more than once in a 6 minute time period",
      "The mode of transmission affects the time period over which the tissue heating effect should be considered",
      "The 6 minute time period is intended to limit the time of continuous heating to a safe level",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1g.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q7",
    question:
      "When operating within the 5MHz band while at a temporary location you must:",
    options: [
      "give your location every 15 minutes",
      "be within reach of a working telephone",
      "limit your power to 100W ERP",
      "limit the antenna height to 15 metres",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1h.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q8",
    question:
      "The drawing shows part of the circuit of a Morse key. The voltage source and 1kΩ resistor are inside the transmitter and the coil is added externally to slow the rise and fall of the keying waveform. What is the time constant of the keying circuit? <br><br><img src='images/rsgb-full-3-q8.png' alt='test'  >",
    options: ["800µs", "800ms", "1.25µs", "1.25ms"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.7",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q9",
    question:
      "The circuit diagram shows an NPN transistor being used as an amplifier. The potential difference across the Base-Emitter junction is 0.6Volt and there is 1V across $R_e$. Which resistor may be used for R1 in order to create the correct transistor bias. You may assume the base current is insignificant. <br><br><img src='images/rsgb-full-3-q9.png' alt='test'  >",
    options: ["8.2k", "10k", "12k", "15k"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2b.1",
    examStrategy: 5,
    examStrategyNotes:
      "I have no idea how to do this at the moment so have a guess and move on.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q10",
    question:
      "Which of the graphs shown shows the characteristics of a Zener diode? Forward bias is shown to the right. <br><br><img src='images/rsgb-full-3-q10.png' alt='test'  >",
    options: ["Graph 2", "Graph 1", "Graph 4", "Graph 3"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2i.1",
    examStrategy: 3,
    examStrategyNotes: "Drill this shape. There are a few flashcards.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q11",
    question:
      "The purpose of a low pass filter in the microphone amplifier of an SDR transmitter prior to the analogue to digital converter (ADC) is to:",
    options: [
      "avoid higher frequency signals causing aliases in the digital representation",
      "prevent excessive bandwidth of the transmitted radio frequency signal",
      "minimise the generation of phase noise in the audio modulator",
      "optimise the average to peak power ratio to give maximum power without over-modulation",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2f.1",
    tagged: true,
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q12",
    question: "The back EMF created when a current changes, is due to the:",
    options: [
      "inductance in a coil of wire carrying the current",
      "increase in voltage as current charges a capacitor",
      "increase in voltage as a secondary cell is charged",
      "voltage across a reverse biased diode in a full wave circuit",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q13",
    question: "A transformer can NOT be used to:",
    options: [
      "produce a greater power output in the secondary winding than the power fed into the primary winding",
      "provide electrical isolation between the primary winding and the secondary winding or windings",
      "produce a different voltage across any of its secondary windings from that fed across the primary winding",
      "match the impedance of a load to the output impedance of a device that is used to power the load",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 2,
    examStrategyNotes: "Ignoring losses, power out is the same as power in.",
    examCalculation: 0,
    exam_NOT: true,
  },
  {
    source: "RSGB Full Mock 3 Q14",
    question:
      "What is the main function of capacitor C3 in the circuit shown? <br><br><img src='images/rsgb-full-3-q14.png' alt='test'  >",
    options: [
      "Providing feedback to stabilise the gain",
      "Decoupling AC signals on the emitter",
      "Coupling AC signals into the transistor",
      "Maintaining a DC voltage on the emitter",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2e.4",
    examStrategy: 1,
    examStrategyNotes: "Siphon off the AC... DRILL!",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q15",
    question:
      "The rectifier diodes in a mains operated 12V stabilised power supply have failed and must be replaced. Which of the following diodes would be chosen to replace them?",
    options: [
      "Diodes with a PIV rating of 12V",
      "Diodes with a PIV and current rating equal to or greater than the original diodes",
      "Diodes with a current rating equal to or greater than the original diodes.",
      "Diodes with a PIV rating equal to or greater than the original diodes",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2j.3",
    examStrategy: 4,
    examStrategyNotes: "Can we find a source for this, and then drill.",
    examCalculation: 0,
    exam_NOT: "",
  },
  {
    source: "RSGB Full Mock 3 Q16",
    question:
      "The drawing shows the response curve of the IF of a receiver, the attenuation of the received audio at 6kHz will be about <br><br><img src='images/rsgb-full-3-q16.png' alt='test'  >",
    options: ["28dB", "3dB", "0dB", "16dB"],
    correct: 3,
    explanation: `The graph shows signal level loss at various frequencies. 
    Attenuation means a loss of signal, so an attenuation of 16dB is 
    exactly the same as a response curve for the signal showing -16dB.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2h.4",
    examStrategy: 4,
    examStrategyNotes: `Remember that an attenuation of 25dB means the response curve will show -25dB. Attenuation means loss, a negative number, so we don't say an attenuation of -16dB. This is a somewhat woolly question, so get used to ambiguity!`,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q17",
    question: "The relative permittivity of a dielectric is a measure of the:",
    options: [
      "amount of voltage permitted on the plates of a capacitor, when fed by a rectifier diode in a power supply",
      "amount by which the core of a coil affects the inductance, when compared with the inductance in a vacuum",
      "ratio of the capacitance with the dielectric to the capacitance in a vacuum",
      "dynamic resistance of a series tuned circuit, when it is fed with a signal at the resonant frequency",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q18",
    question:
      "The diagram shows a bipolar transistor connected as an Emitter-Follower. Other circuit components have been omitted for clarity. Vb and Ve are the peak signal and peak emitter voltages. An important feature of such a circuit is that: <br><br><img src='images/rsgb-full-3-q18.png' alt='test'  >",
    options: [
      "Ve is about 0.6 Volts more than Vb",
      "the signal voltage gain Ve/Vb is always much greater than 1",
      "its input impedance is greater than its output impedance",
      "its output impedance is much greater than its input impedance",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2i.4",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q19",
    question:
      "The drawing shows the spectrum of the input and output of an external RF power amplifier being fed from an SSB transmitter. The most likely explanation for the change in the spectrum is that <br><br><img src='images/rsgb-full-3-q19.png' alt='test'  >",
    options: [
      "standing waves on the feeder are causing multiple reflections",
      "intermodulation products are being generated in the power amplifier",
      "the lower power in the base transmitter is masking its intermodulation products",
      "the power amplifier is not correctly matched to the output of the transmitter",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3f.2",
    examStrategy: 3,
    examStrategyNotes: "Our old friennds the intermodulation products.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q20",
    question:
      "An operator should not overdrive an external power amplifier with a transmitter in order to avoid:",
    options: [
      "spurious inter-modulation products",
      "a high SWR",
      "loss of modulation on FM",
      "exceeding the power permitted in the licence",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3g.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q21",
    question:
      "What is the frequency of the local oscillator of a transverter that enables a 28MHz to 30MHz transceiver to be operated on the 70MHz band?",
    options: ["29MHz", "22MHz", "116MHz", "42MHz"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3c.3",
    examStrategy: 5,
    examStrategyNotes: "More learning materials are needed: Claude?",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q22",
    question:
      "In order to use mathematical processing to tune to and demodulate a radio signal, one can employ a mixing process where the incoming RF signals:",
    options: [
      "are combined in the IF stages to give two copies of the modulation 180 degrees apart",
      "are combined in the IF stages to give two copies of the modulation 90 degrees apart",
      "are mixed with two local oscillator signals of the same frequency but 180 degrees different in phase",
      "are mixed with two local oscillator signals of the same frequency but 90 degrees different in phase",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3m.2",
    examStrategy: 5,
    examStrategyNotes: "More learning materials.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q23",
    question:
      "In a double conversion super-heterodyne receiver, the second mixer will convert:",
    options: [
      "The first IF to the second IF",
      "The second IF to the first IF",
      "The second IF to the third IF",
      "The second IF to AF",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3f.4",
    examStrategy: 3,
    examStrategyNotes:
      "Can we find a reference to this, possible in the second half of the course as its receivers.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q24",
    question:
      "As the Modulation Index of an FM transmission increases it is always the case that the:",
    options: [
      "volume of the received audio signal increases",
      "frequency of the received audio signal increases",
      "number of sidebands required increases",
      "bandwidth of the transmission increases",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3a.2",
    examStrategy: 3,
    examStrategyNotes:
      "It's in the flashcard: we just need to know that they are there and there are more as the Modulation Index increases.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q25",
    question:
      "What signals should be at the points 'P' and 'Q' in the drawing?  <br><br><img src='images/rsgb-full-3-q25.png' alt='test'  >",
    options: [
      "P: audio Q: frequency modulated carrier.",
      "P: amplitude modulated IF Q: audio",
      "P: audio Q: amplitude modulated carrier",
      "P: frequency modulated IF Q: audio.",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3k.1",
    examStrategy: 5,
    examStrategyNotes: "More learning materials.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q26",
    question:
      "What function is performed in the box marked X?    <br><br><img src='images/rsgb-full-3-q26.png' alt='test'  >",
    options: [
      "Fourier transformation",
      "Anti-alias filtering",
      "Sine wave lookup table",
      "Digitally controlled oscillator",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3c.3",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q27",
    question:
      "A receiver is being designed to receive a medium wave broadcast on 1.000MHz. The local oscillator is set to 1.465MHz. For the same IF, what other frequency could the local oscillator be set to?",
    options: ["1000kHz", "535kHz", "1465kHz", "465kHz"],
    correct: 1,
    explanation:
      "The potential answers are reducing the options created by SUM and DIFFERENCE outcomes.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3i.3",
    examStrategy: 4,
    examStrategyNotes:
      "Fairly straightforward. Look at the IF implied by FIRST_LO MINUS WANTED, then work out WANTED MINUS SECOND_LO for the same IF.",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q28",
    question:
      "It is proposed to generate a microwave signal by feeding the output of a UHF transmitter to a frequency multiplier circuit. This arrangement is suitable for use with:",
    options: [
      "single sideband modulation with suppressed carrier",
      "frequency modulation",
      "single sideband modulation with a pilot (reduced) carrier",
      "amplitude modulation",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3d.1",
    examStrategy: 3,
    examStrategyNotes:
      "The key word is MULTIPLIER, which can be used for CW and FM, but not for AM or SSB. There is a flashcard for this.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q29",
    question:
      "A 70cm receiver has a long feeder to an antenna at the far end of the garden. To improve reception of weak signals a good pre-amp is fitted alongside the receiver. The improvement in signal to noise ratio is noticeable but not impressive, certainly only a fraction of the expected improvement given the gain of the pre-amp. To try to further improve matters it is worth:",
    options: [
      "swapping the pre-amp for one of a higher gain",
      "moving the pre-amp to the antenna end of the main feeder",
      "fitting a high-pass filter to remove signals at 2m and below",
      "running the feeder at least 20cm deep in the soil",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3j.1",
    examStrategy: 3,
    examStrategyNotes: "Drill!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q30",
    question:
      "What would be the most serious consequence of an unstable carrier?",
    options: [
      "The transmission could move outside the authorised band",
      "The transmissions could interfere with other amateurs",
      "The receiving station would have difficulty receiving the signal",
      "The transmission could interfere with television receivers",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3c.1",
    examStrategy: 3,
    examStrategyNotes: "Look at the flashcards!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q31",
    question:
      "A 100Ω antenna is feeding a receiver with a 50Ω input impedance. It is decided to improve the matching by inserting a λ/4 length of coaxial cable as an impedance transformer. The characteristic impedance of this cable should be:",
    options: ["100Ω", "72Ω", "50Ω", "300Ω"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4f.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q32",
    question: "Which of the following is NOT a type of balun?",
    options: ["Differential", "Transformer", "Sleeve", "Choke"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4b.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q33",
    question:
      "The maximum potential difference between the conductors of a feeder divided by the minimum potential difference is known as the:",
    options: [
      "return loss",
      "standing wave ratio",
      "vector sum",
      "maximum working voltage",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4e.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q34",
    question:
      "When a signal is applied to the antenna in the diagram the RF voltage is:  <br><br><img src='images/rsgb-full-3-q34.png' alt='test'  >",
    options: [
      "highest at point B",
      "lowest at points C",
      "highest at points A",
      "uniform throughout",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4d.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q35",
    question:
      "The rapid fluttering typical of VHF auroral contacts is caused by:",
    options: [
      "focussing and defocussing of folds in the auroral curtains",
      "the interaction between the radio waves and the charged particles which cause the aurora",
      "the random movements of the auroral curtains which can reflect VHF radio waves",
      "the normal atmospheric scintillation evident over such lengthy auroral paths",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5c.3",
    examStrategy: 3,
    examStrategyNotes: "Think about those auroral curtains fluttering...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q36",
    question:
      "An isotropic fade-out or Sudden Ionospheric Disturbance is normally caused by:",
    options: [
      "prolonged high temperatures",
      "a full moon",
      "a recent solar flare",
      "a sunspot minima",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5b.1",
    examStrategy: 3,
    examStrategyNotes: "Just have to drill this one. It's part of solar flare.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q37",
    question:
      "Under free space conditions at a distance of 10m from a transmitting antenna the field strength is measured as 16 Volts per metre. At double the distance of 20m from the same transmitting antenna, the field strength will:",
    options: [
      "be the same at 16 Volts per metre",
      "be halved to 8 Volts per metre",
      "be quartered 4 Volts per metre.",
      "be doubled to 32 Volts per metre",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5a.1",
    examStrategy: 4,
    examStrategyNotes:
      "(Electric) Field Strength (EFS) is inversely proportional to distance, so get linear.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q38",
    question:
      "An alarm system claims to meet the various standards including EMC and there is no reason to doubt that. However, it is found to react to a neighbour’s radio transmissions on several HF bands. Why might that be?",
    options: [
      "The alarm is good but it has been installed poorly with many unscreened wires.",
      "It is more than 12 months old and the guarantee has expired",
      "The transmissions happen to be on the image frequency of the alarm",
      "The pickup on the alarm wires is differential mode interference",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6a.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q39",
    question:
      "The PN junction in a semiconductor device can be the cause of breakthrough by:",
    options: [
      "generating odd harmonics",
      "rectifying the interfering signal",
      "causing overheating",
      "changing the frequency of the signal",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6c.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q40",
    question:
      "The car handbook states that transmitters over 50W power must not be fitted. Why might this be?",
    options: [
      "Human RF exposure guidelines would be exceeded",
      "The RF field strength would cause a risk of the car electronics malfunction",
      "Transmitting near a petrol filling station could cause an explosion",
      "Car wiring cannot supply the considerable additional current required",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6f.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q41",
    question:
      "The most significant risk using a quarter wave vertical antenna without an RF earth is:",
    options: [
      "excessive noise on receive resulting in an inability to receive weaker signals",
      "RF currents in the mains earth and power leads",
      "difficulty in getting a low SWR on the feeder to the antenna",
      "frequency instability due to RF getting into other sections of the transmitter circuitry",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6e.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q42",
    question: "A home made transceiver must comply with the:",
    options: [
      "EU Radio Equipment Directive 2014/53/EU",
      "EU Electro-Magnetic Compatibility Directive 2014/30/EU",
      "UK Radio Equipment Regulations 1206/2017",
      "Amateur Radio Wireless Telegraphy Licence Conditions Booklet",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6a.4",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q43",
    question:
      "A temporary installation of a transceiver in a vehicle suffers from the transmitter remaining on transmit, despite the PTT being released. It is found that putting ferrite beads on the microphone leads close to the transmitter cures the problem. This is because the:",
    options: [
      "added inductance reduces the RF entering the transceiver microphone socket",
      "ferrite beads act as a high pass filter to the transmitted signal",
      "capacitance across the switch contacts is low at radio frequencies",
      "DC signal for the PTT cannot easily pass through ferrite beads",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6d.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q44",
    question:
      "Which of the following are likely to reduce the generation of passive inter-modulation products at your station?   <br><br><img src='images/rsgb-full-3-q44.png' alt='test'  >",
    options: ["1 and 3", "1 and 2", "3 and 4", "2 and 4"],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6b.3",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q45",
    question:
      "A neighbour contacts you asking if you were on the radio the previous evening as they were experiencing some interference. What is the first thing you should do?",
    options: [
      "Offer to carry out some tests to discover the cause of the interference",
      "Cease all transmissions until the matter is resolved",
      "Refer them to Ofcom",
      "Advise them to fit some ferrite rings to their television system",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6g.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q46",
    question:
      "A transmitter is feeding 400W to an antenna array of four nineteen element Yagis with a combined gain of 23dB. At what distance has the field strength fallen to 3.3 V/m?",
    options: ["2km", "600m", "424m", "86m"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6e.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q47",
    question:
      "A VHF FM radio receiver is being used on 95.8MHz when a distorted voice like sound is noticed alongside the wanted programme. Tuning to other broadcast programmes has minimal effect but the interference is a bit more noticeable on weaker broadcasts. A likely source of the interference is an:",
    options: [
      "FM transmission in the 29MHz amateur band",
      "FM transmission in the 10MHz amateur band",
      "SSB transmission in the 29MHz amateur band.",
      "SSB transmission in the 10MHz amateur band.",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6c.3",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q48",
    question: "What does operating split mean?",
    options: [
      "A station is listening on a frequency a few kHz away from the one it is transmitting on",
      "There are two stations, both using the same club callsign sharing the workload",
      "There are two stations, both using the same club callsign but on different bands",
      "Reception and transmission are in different amateur bands to allow a full duplex contact",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) 11 of the Full Licence text book",
    syllabus: "7a.1",
    week: "1",
    examStrategy: 2,
    examStrategyNotes: "Stay calm.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q49",
    question: "The recommended maximum bandwidth on 473.5kHz is:",
    options: ["3kHz", "1.5kHz", "500Hz", "200Hz"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7b.1",
    examStrategy: 5,
    examStrategyNotes:
      "See Note 1 on the 600m band plan. This is one for the big neon sign.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q50",
    question:
      "To ensure a public amateur radio demonstration does not cause RF fields above a safe level you should check the guidance provided by the:",
    options: ["ICNIRP", "RSGB", "IET or IEEE", "local authority"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8d.1",
    examStrategy: 1,
    examStrategyNotes: "Go for it!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q51",
    question:
      "When operating your station while in charge of a motor vehicle you should:",
    options: [
      "only operate using frequency modulation",
      "ensure you can operate safely without compromising your ability to control the vehicle",
      "not worry about safety as licensed amateurs are exempt from the regulations regarding 'hands free' operation",
      "only operate with a voice operated (VOX) microphone",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8f.5",
    examStrategy: 1,
    examStrategyNotes: "Safety first",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q52",
    question:
      "If a house electrical supply is of the protective multiple earth type (PME), then:",
    options: [
      "tthe house earth is derived from the supply neutral conductor near the point of entry to the house",
      "the householder must make suitable arrangements for their own local safety earth",
      "the house safety earth is provided by a separate conductor from an electricity sub-station.",
      "both the neutral and earth wires in the flex from each appliance must be connected to the neutral pin in the plug",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8a.2",
    examStrategy: 2,
    examStrategyNotes: "Drill this.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q53",
    question:
      "When seeking insurance cover for an event open to the public the insurers will expect:",
    options: [
      "advise the emergency services of the nature and location of the event to allow a speedy response if it is required",
      "to see evidence you have identified the risks involved, sought to minimise risk and outcome and kept records of that process",
      "you to take all due precautions and remember to advise the visiting public what they can and cannot do",
      "you to have guides to keep visitors at a safe distance from masts and other structures that could cause injury",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8f.6",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q54",
    question:
      "Which ONE of the following would be used to check for the second and third harmonics, when using a transmitter which is set to a frequency of 14.150MHz?",
    options: [
      "An RF power meter",
      "An SWR meter",
      "An HF/VHF receiver",
      "A digital frequency meter",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.6",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q55",
    question:
      "To measure the RF output power of a transmitter, the power meter should be:",
    options: [
      "connected as close as possible to the antenna",
      "connected in parallel with the antenna",
      "connected in between the transmitter and its power supply",
      "set to the highest power range to begin with",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.5",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q56",
    question:
      "The dBm is often used to express power with respect to 1mW; that is 0dBm = 1mW. What power is 20dBm?",
    options: ["1000mW", "100mW", "1mW", "10mW"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9b.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 3 Q57",
    question:
      "The drawing shows a potential divider where R1 is 80kΩ and R2 is 20kΩ. Both resistors are 10% tolerance. The output voltage might be lower than its design value by a maximum of: <br><br><img src='images/rsgb-full-3-q57.png' alt='test'  >",
    options: ["100 mV", "180 mV", "200 mV", "300 mV"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2a.1",
    examStrategy: 3,
    examStrategyNotes:
      "Use voltage divider to get the design voltages, then swing one resistor up and the other down to maximise the drop in V2.",
    examCalculation: 3,
    exam_NOT: false,
    obsidianURL:
      "obsidian://open?vault=FULL-LICENCE-COURSE&file=QUESTION%20ANALYSIS%20FOLDER%2Fcomponent_tolerance_voltage_divider",
  },
  {
    source: "RSGB Full Mock 3 Q58",
    question:
      "A 10MHz quartz crystal oscillator is understood to have a negative frequency drift of 2ppm/year. What would you expect its frequency to be, 3 years after calibration?",
    options: ["10.000004 MHz", "9.999996 MHz", "9.999940 MHz", "10.000060 MHz"],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.3",
    examStrategy: 3,
    examStrategyNotes:
      "As it is MHz and ppm the millions cancel out so we are left with 10 x 2 x 3 and that is taken away from 10,000,000",
    examCalculation: 2,
    exam_NOT: false,
  },
]

export default RSGB_FULL_MOCK_3
