const RSGB_FULL_MOCK_2 = [
  {
    source: "RSGB Full Mock 2 Q1",
    question:
      "Which one of the circumstances listed would allow you to pass an encrypted message on behalf of another person?",
    options: [
      "The message contains the name and address of a casualty",
      "The message has been given to you by a member of a User Service",
      "The message contains particularly unpleasant details of injuries",
      "The message has been given to you by the casualty in person",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1c.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q2",
    question:
      "Testing a home-made VFO shows it is stable to about 0.1%. What is the most serious problem you are likely to encounter on-air when using it for transmitting on 14.346 MHz upper sideband?",
    options: [
      "The possibility of transmitting out of band",
      "Interference to non-amateur stations on immediately adjacent bands",
      "Harmonics of your transmission in the 21 and 28MHz amateur bands",
      "The need for your distant contact to retune his receiver occasionally",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1d.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q3",
    question:
      "To control your remote station from your main station, your communication link within an amateur band:",
    options: [
      "must be below 30MHz",
      "must be above 30MHz",
      "must be above 200MHz",
      "must be below 15MHz",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1e.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q4",
    question:
      "An amateur holding the callsign MJ0JKL has <mark>permanently</mark> moved to Italy, which has implemented CEPT Recommendation T/R 61-01. MJ0JKL can:",
    options: [
      "operate under the CEPT agreement using the call I/M0JKL",
      "not operate as M0JKL under the CEPT agreement",
      "operate under the CEPT agreement using the call I/MJ0JKL",
      "operate under the CEPT agreement using the call I/MJ0JKL/P",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7h.1",
    examStrategy: 1,
    examStrategyNotes: `Hopefully you got the memo about the meaning of PERMANENT so 61-02 applies 
    (new reciprocal licence with a new country callsign),
     and can no longer use the temporary 61-01 arrangement.`,
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q5",
    question: "The American continent is classified as:",
    options: ["ITU Region 1", "ITU Region 2", "ITU Region 3", "ITU Region 4"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7h.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q6",
    question:
      "If a check of the EMF compliance distance shows that it extends outside the licensee's private premises and grounds, then it will be necessary to:",
    options: [
      "apply for planning permission to extend the boundary of the premises to cover the affected area",
      "fence off the affected area such that members of the general public cannot gain access without permission",
      "ensure that transmission does not take place if the general public are, or can be expected to be, present in the affected locations",
      "notify both Ofcom and the local authority of the extent of the increase, ensuring that it is no more than the 5 % permitted in the planning regulations",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1g.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q7",
    question:
      "You are operating on the 60m band and form a net with a group of radio amateurs. In order to comply with your licence conditions you must give your callsign:",
    options: [
      "on joining and leaving the net",
      "when contacting other net members",
      "every 30 minutes when you are speaking",
      "when requested to do so by the station controlling the net",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1h.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q8",
    question:
      "What power is dissipated in the resistor in the diagram? <br><br><img src='images/rsgb-full-2-q8.png' alt='test'  >",
    options: ["5.5mW", "1.75mW", "7mW", "14mW"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2b.1",
    examStrategy: 1,
    examStrategyNotes: "It's a straightforward power calculation",
    examCalculation: 1,
    exam_NOT: "",
  },
  {
    source: "RSGB Full Mock 2 Q9",
    question:
      "A small electrolytic capacitor is marked 100µF - 25 V. This means that:",
    options: [
      "the DC voltage, plus the peak value of any superimposed AC voltage applied, must not exceed 25 V",
      "when charged to 25 V it will have a charge of 2,500 coulombs",
      "it should not be connected to an AC voltage source of more than 25 V peak",
      "the polarity does not matter provided the DC supply is below 25V",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.3",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q10",
    question:
      "The drawing shows the circuit of a switching transistor controlling the current in the coil of a relay. The base is fed with regular pulses to cause the relay contacts to close. Which circuit will minimise the voltage spikes caused by the switching? <br><br><img src='images/rsgb-full-2-q10.png' alt='test'  >",
    options: ["Circuit 3", "Circuit 4", "Circuit 1", "Circuit 2"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q11",
    question:
      "The switch S in the diagram is closed at time t=0. Which graph correctly shows the voltage across the coil after the switch is closed? <br><br><img src='images/rsgb-full-2-q11.png' alt='test'  >",
    options: ["Graph 3", "Graph 4", "Graph 1", "Graph 2"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.7",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q12",
    question:
      "In the circuit shown, C2 is used as a:  <br><br><img src='images/rsgb-full-2-q12.png' alt='test'  >",
    options: [
      "frequency matching capacitor",
      "DC blocking capacitor",
      "decoupling capacitor",
      "coupling capacitor",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2e.4",
    examStrategy: 2,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q13",
    question:
      "An analogue to digital converter is sampling at 7000 samples per second. There is a low-level signal present at the ADC input at 3.6kHz. After conversion the signal will be treated as:",
    options: [
      "a signal at 3.4 kHz",
      "a signal at 100 Hz",
      "a wideband noise signal",
      "a signal at 3.6 kHz",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2f.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q14",
    question:
      "A transformer with 25 turns on the primary and 5 turns on the secondary, has a 1kΩ resistor connected to the secondary. The impedance measured at the primary will be:",
    options: ["50kΩ", "5kΩ", "50Ω", "25kΩ"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q15",
    question:
      "The drawing shows the response curve of a single tuned circuit that might be used in the IF of a receiver. If the centre frequency is 100kHz, the Q-factor is approximately:   <br><br><img src='images/rsgb-full-2-q15.png' alt='test'  >",
    options: ["6", "33", "20", "17"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2h.4",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q16",
    question: "In a Field Effect Transistor the:",
    options: [
      "gate is normally forward-biased (with respect to the source), and with more forward bias the channel moves into “enhancement mode”",
      "width of the depletion layer increases rapidly as the forward current between drain and source increases",
      "width of the depletion layer increases rapidly as the forward current between drain and source decreases",
      "gate is normally reverse-biased (with respect to the source), and with more reverse bias, the channel becomes 'pinched off'",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2i.3",
    examStrategy: 4,
    examStrategyNotes: "Need some learning materials for this one",
    examCalculation: 0,
    exam_NOT: "false",
    tagged: true,
  },
  {
    source: "RSGB Full Mock 2 Q17",
    question:
      "One feature of a transistor amplifier biased in class C is that:",
    options: [
      "the levels of distortion are likely to be lower than other classes",
      "a tuned or resonant collector load is normally required",
      "two transistors are required, operating in a push-pull configuration",
      "the supply current tends to be higher than other classes",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2i.4",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q18",
    question:
      "The output voltage of a stabilised mains operated power supply is often controlled by a:",
    options: [
      "series pass transistor with a Zener reference diode",
      "bridge rectifier with series pass transistor",
      "bridge rectifier with a reservoir capacitor",
      "series pass transistor with a reservoir capacitor",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2j.2",
    examStrategy: 3,
    examStrategyNotes: "Controlled is the key word. Think reference.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q19",
    question:
      "For the block diagram of a transmitter, select the response that matches the function of the numbered component blocks.  <br><br><img src='images/rsgb-full-2-q19.png' alt='test'  >",
    options: [
      "1=Frequency Synthesiser, 2=Mixer, 3=Crystal Oscillator, 4=Filter RF Driver",
      "1=Crystal Oscillator, 3=Mixer, 4=Frequency Synthesiser, 5=Filter RF Driver",
      "1=Crystal Oscillator, 3=Mixer, 4=Filter RF Driver, 5=Frequency Synthesiser",
      "1=Frequency Synthesiser, 2=Filter RF Driver, 3=Mixer, 4=Crystal Oscillator",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3b.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q20",
    question:
      "If there is frequency instability in a transmitter, which of the following methods can minimise this?",
    options: [
      "Load the PA stage correctly",
      "Use a regulated power supply",
      "Do not make Morse code dashes too long",
      "Speak at a distance from the microphone",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) 42-43, 51 of the Full Licence text book",
    syllabus: "3c.1",
    examStrategy: 3,
    examStrategyNotes: "Look at the flashcards!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q21",
    question:
      "What is the purpose of the low pass filter in a direct digital synthesiser?",
    options: [
      "To ensure the output frequency of the wanted signal remains stable and accurate",
      "To remove the effects of minor frequency variations associated with the phase comparator",
      "To remove frequencies associated with the step nature of the signal from the DAC",
      "To minimise the effect of requesting a fast rate of tuning to a different output frequency",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3c.3",
    examStrategy: 4,
    examStrategyNotes: "Ned to get this one under control",
    examCalculation: 0,
    exam_NOT: "",
  },
  {
    source: "RSGB Full Mock 2 Q22",
    question:
      "A superhet receiver is tuned to an upper sideband signal on 144.500MHz. The local oscillator is running at 148.500MHz. The sideband filter to admit the signal should be set to:",
    options: [
      "144.500 to 144.503MHz",
      "4.000 to 4.003MHz",
      "144.493 to 144.500MHz",
      "3.997 to 4.000MHz",
    ],
    correct: 3,
    explanation:
      "The keywords are upper sideband signal (USB), so assume we have 3kHz audio bandwidth, so 144.500 to 144.503MHz in order low to high frequency. After mixing with 148.500MHz Local Oscillator (LO), we focus on the difference products, so 148.500 - 144.500 = 4.000MHz (low f) and 148.500 - 144.503 = 3.997MHz (high f). Because this is <mark>LO - RF</mark> this is called 'high side injection' and the audio gets inverted.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3e.2",
    examStrategy: 4,
    examStrategyNotes:
      "Taking it step by step. Can you remember the rule about inversion? If not just do the low and high frequency calculations and you will see the inversion.",
    examCalculation: 3,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q23",
    question:
      "A transmitter is normally used on SSB and runs comfortably warm even when peaking at 100W output. It is decided to use the same transmitter on RTTY (radio teletype) and the input level is set so the RF output peaks at the same level as previously used on voice. It is likely that the transmitter will run:",
    options: [
      "a bit cooler than before",
      "considerably hotter than before",
      "slightly hotter than before",
      "at much the same temperature as before",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3f.4",
    tagged: true,
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q24",
    question:
      "An RF power amplifier (PA) is specified as 200W output and 10dB gain. An input of 25W from the transceiver driving the PA is likely to result in:",
    options: [
      "additional signals close in frequency to those at the input being produced in the PA",
      "the transceiver showing an increase in the SWR at its output",
      "the PA receiving an overload (ALC) control signal from the transceiver",
      "third order harmonics being present in the transceiver output",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3g.2",
    examStrategy: 3,
    examStrategyNotes: "Learning materials wanted: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q25",
    question:
      "The ratio between the input signal that can just be heard on a receiver and the signal level at which it overloads is known as the receiver’s:",
    options: [
      "noise factor",
      "overload margin",
      "receive threshold",
      "dynamic range",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3h.3",
    examStrategy: 1,
    examStrategyNotes: "This is drilling!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q26",
    question: "Phase noise is a feature often associated with an:",
    options: [
      "AF amplifier",
      "amplifier operating in class C",
      "oscillator",
      "amplifier operating in class A",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3i.5",
    examStrategy: 2,
    examStrategyNotes: "Drill",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q27",
    question:
      "If a pre-amplifier with 6dB gain and a sensitivity of 0.15µV for 10dB signal to noise is added to a receiver of identical sensitivity then the sensitivity will be:",
    options: [
      "slightly poorer (less sensitive)",
      "increased by 6dB",
      "slightly better (more sensitive)",
      "unchanged",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3j.1",
    examStrategy: 5,
    examStrategyNotes: "More learning materials",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q28",
    question:
      "What settings might be provided to operate the AGC in a receiver?",
    options: [
      "Attack/decay; fast/slow",
      "Forward/reverse; high/low",
      "CW/data; on/off",
      "Data/voice; high/low",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3l.1",
    examStrategy: 4,
    examStrategyNotes: "More learning materials.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q29",
    question: "Modulating a carrier with digital data can:",
    options: [
      "vary the amplitude and phase of the carrier",
      "only vary the phase of the carrier",
      "only vary the amplitude of the carrier",
      "only vary the frequency of the carrier",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3m.1",
    examStrategy: 4,
    examStrategyNotes: "More learning materials needed.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q30",
    question:
      "When operating HF SSB in a net of several stations, it is noted that the stations are all transmitting on slightly different frequencies. A good way of improving reception is to adjust the:",
    options: [
      "main frequency or tuning control",
      "IF filter bandwidth",
      "RIT control",
      "squelch",
    ],
    correct: 2,
    explanation:
      "[[ What is the RIT control? Receiver Incremental Tuning allows fine-tuning of the receive frequency, without affecting the transmit frequency, useful in SSB and CW modes, where small frequency mismatches can make voices sound off-pitch or CW tones drift.]]  [[ From the manual: When in contact on SSB with several stations in a net it is possible that they will all be on slightly different frequencies resulting in tonal differences in the received audio which may make understanding difficult. Tuning each station in clearly will also affect your transmitted frequency resulting in everybody in the net having to re-adjust every time. To avoid that a facility called Receiver Incremental Tuning (RIT) can make fine adjustments to the receive frequency without affecting the main frequency setting and the transmitted frequency.]]",
    lookup: "See page(s) 50 of the Full Licence text book",
    syllabus: "3n.1",
    examStrategy: 3,
    examStrategyNotes: "Receiver Incremental Tuning (RIT) might be helpful?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q31",
    question:
      "The drawing shows a sleeve balun. How long should the sleeve be and at which end should the sleeve be connected to the outer braid of the coaxial feeder? <br><br><img src='images/rsgb-full-2-q31.png' alt='test'  >",
    options: [
      "Connected at end B and a half of a wavelength long",
      "Connected at end B and a quarter of a wavelength long",
      "Connected at end A and a half of a wavelength long",
      "Connected at end A and a quarter of a wavelength long",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4b.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q32",
    question:
      "The length of ONE SIDE of a half-wave dipole for 10MHz mounted clear of local obstructions will be approximately:",
    options: ["7.1m", "15.0m", "7.50m", "6.7m"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4d.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q33",
    question:
      "If RF losses in a feeder are high the SWR measured at the transmitter will be:",
    options: [
      "matched to the feeder",
      "the same as the return loss",
      "higher than that at the antenna",
      "lower than that at the antenna",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4e.3",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q34",
    question:
      "A 100Ω antenna is feeding a receiver with a 50Ω input impedance. It is decided to improve the matching by inserting a λ/4 length of coaxial cable as an impedance transformer. The characteristic impedance of this cable should be:",
    options: ["100Ω", "50Ω", "72Ω", "300Ω"],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4f.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q35",
    question: "Communications with amateur satellites should preferably use:",
    options: [
      "orthogonal polarisation",
      "circular polarisation",
      "transverse polarisation",
      "vertical polarisation",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5a.3",
    examStrategy: 4,
    examStrategyNotes:
      "Circular polarisation is often used because the orientation of the satellite is indeterminate.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q36",
    question:
      "A specific feature of NVIS contacts is that the frequency employed is:",
    options: [
      "close to the Critical Frequency",
      "always below the Critical Frequency",
      "about half the Critical Frequency",
      "always above the Critical Frequency",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5b.3",
    examStrategy: 3,
    examStrategyNotes: "More drill work on this one.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q37",
    question:
      "What is the signal level at the receiver if the transmit power is 36dBm and given the link budget parameters below? <br><br><img src='images/rsgb-full-2-q37.png' alt='test'  >",
    options: ["-60dBW", "-60dBm", "-80dBm", "-90dBm"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5d.2",
    examStrategy: 3,
    examStrategyNotes:
      "Just take it steady. Until we know otherwise take the units at the start and keep them until the end.",
    examCalculation: 3,
    exam_NOT: false,
    obsidianURL:
      "obsidian://open?vault=FULL-LICENCE-COURSE&file=QUESTION%20ANALYSIS%20FOLDER%2FCONCEPT%20MODULE%20FOR%20WEEK10%2Flink_budget",
  },
  {
    source: "RSGB Full Mock 2 Q38",
    question:
      "To simplify the installation of an alarm system a single wire is run from the control unit through each sensor in series round the house and then back to the control unit. A risk with this approach is that:",
    options: [
      "the loop needs to be balanced to achieve adequate immunity to RF",
      "the loop will radiate RF which may interfere with TV reception",
      "there is a high likelihood of the wiring picking up RF transmissions",
      "it will be slightly harder to determine which sensor has triggered the alarm",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6a.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q39",
    question:
      "Which mode is least likely to cause the form of interference known as cross modulation?",
    options: ["FM", "CW", "SSB", "AM"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6b.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q40",
    question:
      "If an amateur’s HF transmission enters a TV system via a masthead pre-amplifier the breakthrough is likely to be caused by:",
    options: [
      "unwanted mixer products in the masthead pre-amplifier",
      "harmonics of the amateur transmission",
      "cross-modulation in the masthead pre-amplifier",
      "unwanted mixer products in the TV receiver",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6c.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q41",
    question:
      "It is noticed that when listening to the amplitude modulated air traffic control transmissions around 134MHz a nearby 2m FM transmission causes the sound to stop. This effect is known as:",
    options: ["intermodulation", "cross-modulation", "muting", "blocking"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6c.3",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q42",
    question:
      "Breakthrough on one particular frequency is best cured by which one of the following?",
    options: [
      "Balun",
      "Notch filter",
      "Ferrite bead or beads",
      "Low-pass filter",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6d.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q43",
    question:
      "A Mains supply filter that could be fitted to a transmitter power supply generally consists of: ",
    options: [
      "An arrangement of coils wound on ferrite cores and capacitors configured as a 50Hz band stop (notch) filter",
      "An arrangement of coils wound on ferrite cores and capacitors configured as a high pass filter",
      "An arrangement of coils wound on ferrite cores and capacitors configured as a low pass filter",
      "An arrangement of coils wound on laminated iron cores and capacitors to form a 50Hz band pass filter",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6d.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q44",
    question:
      "Why is it recommended that your transmit power is reduced to no more that that required to maintain the contact?",
    options: [
      "It is a mandatory condition of the Full Licence",
      "It reduces the probability of causing interference to nearby electronic devices",
      "It allows the transmitter to run a higher duty cycle without overheating",
      "More amateur contacts can be achieved without mutual interference",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6e.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q45",
    question:
      "Why is it difficult to achieve a good RF ground when the transmitter is in an upstairs room of a house or building?",
    options: [
      "The earth rods should be sited several metres from the building and any mains safety earths which is difficult to achieve",
      "The distance to the actual ground is a substantial portion of a wavelength so impedance transformation effects need to be considered",
      "The vertical RF earth is likely to radiate which will adversely affect the wanted radiation pattern as well as risk EMC problems",
      "The inductance of a few metres of wire or braid results in a high reactance, typically over 1kΩ which limits the effectiveness",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6e.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q46",
    question:
      "Powering a transmitter in a car, via the cigarette lighter (accessory) socket is:",
    options: [
      "ill advised because the lighter socket is intended for intermittent use only",
      "acceptable if the current required will not exceed about 5A",
      "simple and safe solution for temporary installations",
      "ill advised because of the risk of RF entering the car electronics",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6f.2",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q47",
    question:
      "A neighbour complains to you that they are suffering from interference on a landline telephone. You should advise the neighbour to contact:",
    options: [
      "their telecommunications service provider",
      "Ofcom",
      "the Radio Society of Great Britain",
      "the local authority",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6g.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q48",
    question:
      "The rare island station you are trying to contact often says 'receiving five down'. This means that:",
    options: [
      "it is looking for distant stations coming in at less than S5 in signal strength",
      "it will take five more contacts before pausing for a rest or change of band",
      "it is listening for contacts about 5kHz lower in frequency than transmitting",
      "it is trying to separate out callers using the IOTA reference numbers",
    ],
    correct: 2,
    explanation: "This is a SPLIT frequency question.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7a.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q49",
    question:
      "When calling CQ using SSB the band appears to be occupied by RTTY and other data signals. This may be because:",
    options: [
      " strong broadcast transmitter is causing 'rusty bolt' intermodulation",
      "the band plan in other countries may be different to the UK plan",
      "other amateurs are operating in contravention of the band plans",
      "anomalous propagation is causing cross-modulation effects.",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7b.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q50",
    question:
      "Valve equipment presents a higher risk to safety than solid state equipment mainly because:",
    options: [
      "higher electrical potentials are likely to be present",
      "more radio frequency energy is produced",
      "valves emit non-ionising radiation",
      "there may be broken glass inside the equipment",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8a.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q51",
    question: "The static charge from thunderclouds can ionise the air to:",
    options: [
      "allow exceptionally good VHF propagation for several hours",
      "allow exceptionally good HF propagation for several hours",
      "form a low resistance path to ground enabling a very high current to flow as a lightning strike",
      "form a high resistance path to ground allowing the static charge to safely bleed away",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8e.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q52",
    question:
      "A significant risk in a motor vehicle, not normally a problem in a house is:",
    options: [
      "the lower height and movement of the vehicle causing lower signal strength and deep fades",
      "the Doppler effect associated with the vehicle speed",
      "interference and EMC issues to many more people and houses as the vehicle moves",
      "chafing of wires and resulting possibility of shorting to the electrical earth",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8f.5",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q53",
    question: "A risk assessment should be carried out:",
    options: [
      "in response to a third party claim following an incident",
      "as part of the normal planning for any event",
      "when requested by an appropriate authority",
      "immediately after an accident when all the details are fresh",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8f.6",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q54",
    question:
      "The circuit shown is connected to a supply of 24V. R1 is 20kΩ and R2 is 10kΩ. The voltmeter reads 0-15V and has a resistance of 10kΩ. Approximately what voltage will it read? <br><br><img src='images/rsgb-full-2-q54.png' alt='test'  >",
    options: ["8V", "12V", "15V", "5V"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q55",
    question:
      "An oscilloscope is being used with a half-wave dipole antenna to monitor a received signal. The trace shows 282mV peak-to-peak. However when you also connect this assembly to your radio receiver it shows 6dB lower. Why?",
    options: [
      "Your previous observation was of the peak voltage, not the peak-to-peak voltage",
      "In disconnecting the oscilloscope you also inadvertently disconnected the audio to the transmitter",
      "The receiver has a 50Ω input impedance for correct matching to 50Ω systems",
      "Your previous observation did not allow for peak-to-peak to RMS conversion",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.4",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q56",
    question:
      "A device that measures forward and reflected power on a transmission line is a description of:",
    options: [
      "a heterodyne wavemeter",
      "a signal strength meter",
      "an absorption wavemeter",
      "an SWR meter",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.7",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q57",
    question: "The decibel may be used to measure:",
    options: [
      "power ratios, where multiplying the power by 10 represents an increase of 10 decibels",
      "voice quality at a microphone, on a scale which allows the equipment to be used without suffering distortion",
      "differences between various types of amplifier, with 0 decibels as the least efficient, and 100 decibels as the most efficient",
      "voltage ratios, where multiplying the PD by 10 represents an increase of 10 decibels",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9b.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 2 Q58",
    question:
      "The drawing shows a Field Effect Transistor (FET) circuit biased by R1 and R2. R1 is 80kΩ and R2 is 20kΩ. Both resistors are 10% tolerance.The bias voltage might be lower than its design value by a maximum of:  <br><br><img src='images/rsgb-full-2-q58.png' alt='test'  >",
    options: ["180mV", "100mV", "300mV", "200mV"],
    correct: 2,
    explanation:
      "Lowest voltage in R2 is when R1 is increased by 10% and R2 is decreased by 10%. So, R2 gets 10V x 1.8/(1.8 + 8.8) which comes to 1.7V, so the answer is 300mV.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2a.1",
    examStrategy: 1,
    examStrategyNotes: "",
    examCalculation: 0,
    exam_NOT: false,
  },
]

export default RSGB_FULL_MOCK_2
