const RSGB_FULL_MOCK_1 = [
  {
    source: "RSGB Full Mock 1 Q1",
    question:
      "You are helping at a field first aid post tent run by St John Ambulance when a paramedic asks you to send a message relating to a particular patient. It is clear that some details are deliberately obscured. You should:",
    options: [
      "pass the message omitting the obscured parts",
      "ask for the obscured details to be clarified",
      "decline to send the message because its meaning is obscured",
      "pass the message exactly as written",
    ],
    correct: 3,
    explanation:
      "This is a direct request from a User Service. There is a list in EX309 of User Service",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1c.1",
    examStrategy: 3,
    examStrategyNotes: "Well drilled",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q2",
    question: "Your Licence requires that your amateur station MUST NOT cause:",
    options: [
      "any interference to electrical or electro-mechanical devices",
      "any interference to other radio users",
      "undue interference to any electrical equipment",
      "undue interference to other wireless telegraphy",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1d.1",
    examStrategy: 1,
    examStrategyNotes: "Well drilled.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q3",
    question:
      "Which of the following pairs of frequencies should be used for wireless links established for the purpose of Remote Control Operation?",
    options: [
      "136kHz and 1.8MHz",
      "50MHz and 432MHz",
      "28MHz and 144MHz",
      "21MHz and 28MHz",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1c.1",
    examStrategy: 3,
    examStrategyNotes: "See EX309 6-10b",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q4",
    question:
      "An amateur holding the callsign MW0XYZ has <mark>permanently</mark> moved to Portugal, which has implemented CEPT Recommendation T/R 61-01. MW0XYZ can:",
    options: [
      "operate under the CEPT agreement using the call CT/MW0XYZ/P",
      "not operate as M0XYZ under the CEPT agreement",
      "operate under the CEPT agreement using the call CT/M0XYZ",
      "operate under the CEPT agreement using the call M0XYZ",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7h.1",
    examStrategy: 3,
    examStrategyNotes: `Look out for words like PERMANENT & RELOCATED which indicate that 
    CEPT T/R 61-02 is now in force which means HAREC, Full reciprocal licence, and new local country callsign.
    The temporary (visitor) use of UK callsign under CEPT T/R 61-01 is no longer available.`,
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q5",
    question:
      "When on a ship in international waters between Australia and New Zealand the frequencies allocated to amateur radio may be found in:",
    options: [
      "The Schedule to the UK licence",
      "The ITU Radio Regulations for Region 2",
      "The ITU Radio Regulations for Region 3",
      "The Schedule to the Australian licence",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7h.2",
    examStrategy: 1,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q6",
    question:
      "What is the area over which the general public need to be protected from electromagnetic fields exceeding the specified limits?",
    options: [
      "The area identified by a compliance check based on the ITU guidelines",
      "The area identified by a compliance check based on ICNIRP guidelines",
      "The premises and ground area given by the Main Station Address",
      "The premises and ground area currently in use by the station",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1g.1",
    examStrategy: 4,
    examStrategyNotes: "Drill.",
    examCalculation: 0,
    exam_NOT: false,
    tagged: true,
  },
  {
    source: "RSGB Full Mock 1 Q7",
    question:
      "A UK amateur you are talking to on 5MHz insists their licence requires them to give their Callsign when they leave the net you are part of. They are:",
    options: [
      "the holder of a Foundation licence operating under supervision",
      "probably confusing the style of operating in a different radio service",
      "correct in their belief because that requirement applies to any net",
      "correct in their belief because the net is being conducted in the 5MHz band",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "1h.1",
    examStrategy: 1,
    examStrategyNotes:
      "It's the 5MHz band. See Note G which has 9 clauses about this band, including VI-1, which says the licensee shall transmit the station Call sign when first joining the net and on leaving it.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q8",
    question:
      "A transmitter delivers an RF current of 0.5A into a 50Ω dummy load. The power dissipated in the dummy load is:",
    options: ["50W", "12.5W", "25W", "0.5W"],
    correct: 1,
    explanation:
      "Combining $P = V \\cdot I$ and $V = I \\cdot  R$ we get $P = I^2 \\cdot R$. Then using $\\frac{1}{2}$ for 0.5 the math is easy.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2b.1",
    examStrategy: 1,
    examStrategyNotes:
      "The maths is easy if $\\frac{1}{2}$ is used instead of 0.5.",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q9",
    question: "The relative permittivity of a dielectric is a measure of the:",
    options: [
      "dynamic resistance of a series tuned circuit, when it is fed with a signal at the resonant frequency",
      "amount by which the core of a coil affects the inductance, when compared with the inductance in a vacuum",
      "change in capacitance compared to a capacitor of the same dimensions in a vacuum",
      "amount of voltage permitted on the plates of a capacitor, when fed by a rectifier diode in a power supply",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.1",
    examStrategy: 1,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q10",
    question:
      "In the case of self-inductance, the magnetic field created by a changing:",
    options: [
      "voltage induces a current in the same circuit",
      "voltage induces a resistance in the same circuit",
      "current induces a voltage in the same circuit",
      "resistance induces a voltage in the same circuit",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.4",
    examStrategy: 2,
    examStrategyNotes: "Another way of asking the very same thing.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q11",
    question:
      "On applying a constant voltage, V, to a resistor-capacitor series combination the current, I:",
    options: [
      "falls from an initial value equal to V/R towards zero",
      "is always equal to zero",
      "is initially zero and rises to a value equal to V/R",
      "may be calculated by Ohms Law and is constant",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2d.7",
    examStrategy: 1,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q12",
    question:
      "A resistor of 4000Ω and a capacitor of 27pF are connected in series. What is the impedance of the combination at 1.965MHz?",
    options: ["7000Ω", "5000Ω", "3000Ω", "5300Ω"],
    correct: 1,
    explanation:
      " See EX309 C3R4 and C1R6. $X_C = \\frac{1}{2 \\cdot \\pi \\cdot f \\cdot C}$. Pythagoras may be helpful.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2e.6",
    examStrategy: 4,
    examStrategyNotes:
      "See EX309 for REACTANCE of a capacitor, then Impedance in terms of Resistance and Reactance. Pythagoras is your friend! Actually a Pythagorean guess might be good if all else fails.",
    examCalculation: 2,
    exam_NOT: "",
  },
  {
    source: "RSGB Full Mock 1 Q13",
    question: "The process termed a Fast Fourier Transform:",
    options: [
      "samples the signals picked up by the antenna and separates them out into signals in frequency order",
      "produces two digital representations of RF or IF signals separated in phase by 90 degrees",
      "demodulates data signals into their original binary format for subsequent processing",
      "relies on the mutual inductance between two coils normally set 90 degrees apart.",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2f.2",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q14",
    question: "A transformer can NOT be used to:",
    options: [
      "produce a greater power output in the secondary winding than the power fed into the primary winding",
      "provide electrical isolation between the primary winding and the secondary winding or windings",
      "produce a different voltage across any of its secondary windings from that fed across the primary winding",
      "match the impedance of a load to the output impedance of a device that is used to power the load",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2g.1",
    examStrategy: 1,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: true,
  },
  {
    source: "RSGB Full Mock 1 Q15",
    question: "A quartz crystal:",
    options: [
      "has an equivalent circuit which includes a diode, two inductors and a single capacitor",
      "will resonate at several design frequencies, selected by an adjustment on the side of the crystal holder",
      "has a single resonant frequency: whether series or parallel depends on the manufacturing process",
      "has series and parallel resonant frequencies with the associated circuit design selecting the one required",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2h.2",
    examStrategy: 2,
    examStrategyNotes: "Just have to drill this one",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q16",
    question:
      "In the field-effect transistor, the ‘pinch-off’ voltage is the bias required on the:",
    options: [
      "gate to reduce the drain-source current to zero",
      "drain to reduce the gate-drain current to zero",
      "source to reduce the gate-source current to zero",
      "source to reduce the source-drain current to zero",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2i.3",
    examStrategy: 4,
    examStrategyNotes: `Will we ever understand how transistors work? In the meantime,
    the Gate is used to control the path between Source and Drain, so this turns out to be a simple question to answer.
    Just don't get too involved if it's not obvious. Have an educated guess!
    `,
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q17",
    question: "In an oscillator the gain in the transistor amplifier must be:",
    options: [
      "slightly greater than the loss in the feedback",
      "greater than 1/(beta) of the transistor.",
      "slightly more than one",
      "not less than the value of beta of the transistor",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2i.5",
    examStrategy: 3,
    examStrategyNotes: "Need some learning materials on this - Claude?",
    examCalculation: 0,
    exam_NOT: false,
    tagged: true,
  },
  {
    source: "RSGB Full Mock 1 Q18",
    question:
      "If the secondary voltage from the transformer is 10V rms the peak inverse voltage rating (PIV) of the diode should be at least: <br><br><img src='images/rsgb-full-1-q18.png' alt='test'  >",
    options: ["10V", "20V", "15V", "30V"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "2j.3",
    examStrategy: 5,
    examStrategyNotes: "Need some learning materials: Claude?",
    examCalculation: 1,
    exam_NOT: false,
    tagged: true,
  },
  {
    source: "RSGB Full Mock 1 Q19",
    question: "The Modulation Index of an RF signal is the ratio of:",
    options: [
      "the maximum frequency deviation to the nominal unmodulated carrier frequency",
      "the amplitude of the unmodulated carrier to the variation in amplitude of the envelope",
      "the frequency deviation from the nominal carrier frequency to the frequency of the audio signal",
      "the instantaneous frequency deviation from the nominal carrier frequency to the maximum deviation",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3a.2",
    examStrategy: 2,
    examStrategyNotes: "Drill",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q20",
    question:
      "If the frequency of the master oscillator in a transmitter drifts, then:",
    options: [
      "the depth of modulation will vary",
      "Morse signals will change frequency during each ‘dit’ and ‘dah’",
      "the sidebands on AM and SSB may be inverted",
      "the transmitted frequency will change",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3c.1",
    examStrategy: 3,
    examStrategyNotes:
      "This is always very, very bad, so look for the worst outcome, especially into non-amateur bands.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q21",
    question: "The look-up table in a direct digital synthesiser:",
    options: [
      "records the frequency, step size and maximum/minimum frequencies",
      "contains the amplitude of a sine wave at different points in the cycle",
      "keeps track of the division ratio of the VFO output signal",
      "contains frequency corrections for the temperature of the crystal reference",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3c.3",
    examStrategy: 1,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q22",
    question:
      "It is proposed to generate a microwave signal by feeding the output of a UHF transmitter to a frequency multiplier circuit. This arrangement is suitable for use with:",
    options: [
      "amplitude modulation",
      "single sideband modulation with suppressed carrier",
      "frequency modulation",
      "single sideband modulation with a pilot (reduced) carrier",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3d.1",
    examStrategy: 3,
    examStrategyNotes:
      "The key word is MULTIPLIER, which can be used for CW and FM, but not for AM or SSB. There is a flashcard for this.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q23",
    question:
      "A class AB transmitter has been in use for some time and the speech processor is then switched on and set to maximum compression. The peak transmit power is seen to be unaffected. It is LIKELY that the transmitter will run:",
    options: [
      "considerably hotter than before",
      "slightly hotter than before",
      "a bit cooler than before",
      "at much the same temperature as before",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3f.4",
    examStrategy: 1,
    examStrategyNotes: "Drill",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q24",
    question: "Which of the following is most likely to cause harmonics?",
    options: [
      "a tuned half-wave antenna",
      "connecting the transmitter to a dummy load",
      "an overdriven PA stage",
      "an unscreened power supply unit",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3g.3",
    examStrategy: 2,
    examStrategyNotes: "Overdriving always leads to trouble",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q25",
    question:
      "A receiver can just audibly detect signals of 0.4μV (-145dBW) at its input. The receiver overloads at an input of 10mV(-57dBW) causing intermodulation products that can be heard as false signals. The dynamic range of the receiver is:",
    options: ["202dB", "88dB", "145dB", "57dB"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "0",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q26",
    question:
      "The selectivity of a superheterodyne receiver is determined mainly by the:",
    options: [
      "IF amplifier",
      "detector",
      "audio amplifier",
      "frequency changer",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3i.4",
    examStrategy: 2,
    examStrategyNotes: "In the IF stage, we add gain and selectivity.",
    examCalculation: 0,
    exam_NOT: false,
    tagged: true,
  },
  {
    source: "RSGB Full Mock 1 Q27",
    question:
      "It is often found that adding a preamplifier to an HF receiver has little effect on the signal to noise ratio of weak signals. Why might this be so?",
    options: [
      "The extra gain will reduce the overload margin so intermodulation effects will mask any improvement",
      "Natural HF noise is relatively high, an antenna sited pre-amplifier will have little or no effect on the received SNR",
      "Preamps are wideband devices so will pick up a wider range of noise which will reduce the overall noise performance",
      "HF amplifiers are inherently noisy so a preamp is unlikely to be any better than the receiver it is to be used with",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3j.1",
    examStrategy: 4,
    examStrategyNotes:
      "For HF, probably the only valid use of a pre-amplifier for anything except weak signals might be to mount it next to the antenna.",
    examCalculation: 0,
    exam_NOT: false,
    tagged: true,
  },
  {
    source: "RSGB Full Mock 1 Q28",
    question: "Which mode of signals is demodulated with a ratio detector?",
    options: ["FM", "SSB", "AM", "CW"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3k.1",
    examStrategy: 4,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q29",
    question:
      "If the amplitude and phase of an incoming RF signal can be captured with reasonable accuracy then",
    options: [
      "it is not possible to demodulate digital data signals",
      "it is possible to demodulate only frequency modulated signals",
      "it is possible to demodulate any known form of modulation",
      "it is possible to demodulate only digital data signals",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3m.1",
    examStrategy: 4,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q30",
    question:
      "A transceiver will often share circuits between transmitter and receiver. Typically this would include the:",
    options: [
      "frequency modulator",
      "discriminator",
      "AGC circuits",
      "IF filters",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "3n.1",
    examStrategy: 4,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q31",
    question: "Which of the following is NOT a type of balun?",
    options: ["Transformer", "Sleeve", "Differential", "Choke"],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4b.1",
    examStrategy: 2,
    examStrategyNotes: "Drill",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q32",
    question:
      "How long is a typical half wave dipole tuned for the centre of the 1.8MHz band?",
    options: ["52.75m", "75.00m", "157.48m", "78.74m"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4d.1",
    examStrategy: 5,
    examStrategyNotes:
      "This particular question does not succumb to the usual maths. Perhaps something to do with the centre of the 1.8MHz band? Yes, see EX309 and band is from 1.810-2.000MHz. Answer is about 74.8m - will just have to look out for this twist!",
    examCalculation: 3,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q33",
    question:
      "The return loss of a feeder and antenna is measured as 30dB. If the feeder has a loss of 3dB, the return loss of the antenna is:",
    options: ["33dB", "27dB", "36dB", "24dB"],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4e.3",
    examStrategy: 3,
    examStrategyNotes: "This is a straightforward RETURN LOSS question.",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q34",
    question:
      "The diagram shows: <br><br><img src='images/rsgb-full-1-q34.png' alt='test'  >",
    options: ["a 1:4 Balun", "a pi match AMU", "a 1:1 Balun", "an L match AMU"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "4f.1",
    examStrategy: 3,
    examStrategyNotes: "Drill!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q35",
    question:
      "When travelling away from a transmitter on clear ground, it is noted that the '(Electric) Field Strength' has halved. The 'Power Flux Density (PFD)' can be expected to:",
    options: [
      "remain more or less constant",
      "have reduced by a factor of about √ 2 (square root 2)",
      "have halved",
      "have reduced to a quarter of its initial value",
    ],
    correct: 3,
    explanation:
      "From p78: PFD is radio energy (related to the strength of the electric and magnetic components of the electromagnetic field) falling on one square metre at a given distance from the antenna, so at twice the given distance the PFD will be a quarter, equivalent to a signal strength meter drop of 6dB (-3dB is a half so another -3dB gets to a quarter) or one S-point.",
    lookup: "See page(s) 78, 85 of the Full Licence text book",
    syllabus: "5a.1",
    examStrategy: 4,
    examStrategyNotes:
      "EFS falls off in linear fashion, but PFD falls off in inverse square. So, an EFS reduction of 1/2 becomes a PFD reduction of 1/4.",
    examCalculation: 1,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q36",
    question:
      "The Critical Frequency (CF) and Maximum Usable Frequency (MUF) for local and long distance (DX) contacts depend on ionospheric conditions. Which of the lists correctly shows the various frequencies is ascending numerical order? <br><br><img src='images/rsgb-full-1-q36.png' alt='test'  >",
    options: ["Set 4", "Set 1", "Set 3", "Set 2"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5b.2",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q37",
    question: "Galactic noise is most likely to influence reception when:",
    options: [
      "making auroral contacts",
      "receiving from satellites",
      "operating EME (Earth-Moon-Earth)",
      "making HF ionospheric contacts",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "5d.1",
    examStrategy: 3,
    examStrategyNotes:
      "Think the weakest of weak signals from a very long way away.",
    examCalculation: 0,
    exam_NOT: false,
    obsidianURL:
      "obsidian://open?vault=FULL-LICENCE-COURSE&file=QUESTION%20ANALYSIS%20FOLDER%2FCONCEPT%20MODULE%20FOR%20WEEK10%2Fgalactic_noise",
  },
  {
    source: "RSGB Full Mock 1 Q38",
    question:
      "A neighbour has a new television of very good quality installed in his lounge. Nonetheless there are instances of interference from nearby amateur and CB transmissions. It would be sensible to check if the:",
    options: [
      "aerial and its downlead may have deteriorated since they were installed",
      "mains voltage to the premises is below the required level",
      "television has the latest firmware programming installed",
      "affected premises does not have a suitable RF earth system",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6a.2",
    examStrategy: 3,
    examStrategyNotes:
      "Immunity can be adversely affected by poor installation.",
    examCalculation: 0,
    exam_NOT: false,
    clipId: "week12-clip-002",
  },
  {
    source: "RSGB Full Mock 1 Q39",
    question: "Cross modulation is an effect that occurs when:",
    options: [
      "the receiver has inadequate rejection on its image frequency",
      "strong RF signals enter the RF stage of a receiver causing non-linearity",
      "both the wanted signal and the local oscillator signal are modulated",
      "different signals are present on the two sidebands of an AM transmission",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6b.2",
    examStrategy: 3,
    examStrategyNotes: "Review the clip.",
    examCalculation: 0,
    exam_NOT: false,
    clipId: "week12-clip-006",
  },
  {
    source: "RSGB Full Mock 1 Q40",
    question: "Cross modulation is an effect that occurs when:",
    options: [
      "both the wanted signal and the local oscillator signal are modulated",
      "the receiver has inadequate rejection on its image frequency",
      "strong RF signals enter the RF stage of a receiver causing non-linearity",
      "different signals are present on the two sidebands of an AM transmission",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6b.2",
    examStrategy: 3,
    examStrategyNotes: "Watch the clip",
    examCalculation: 0,
    exam_NOT: false,
    clipId: "week12-clip-006",
  },
  {
    source: "RSGB Full Mock 1 Q41",
    question: "One probable cause of mains borne interference is:",
    options: [
      "the choice of power amplifier transistors",
      "an antenna which is positioned too close to an overhead power supply cable",
      "a highly inductive mains supply",
      "harmonics generated in the power amplifier stage",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6c.1",
    examStrategy: 3,
    examStrategyNotes: "Find a clip!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q42",
    question:
      "A domestic VHF FM radio receiver is noticeably more sensitive to interference from a neighbour's HF transmitter when on the 3.5MHz band than on other HF bands.This is likely to be due to:",
    options: [
      "a harmonic of the transmission getting into receiver IF stages",
      "the polar diagram of the amateur antenna having a lobe in the direction ofthe VHF radio",
      "the house mains wiring being resonant at that frequency",
      "the dimensions of the receiver being such that direct pick-up is more efficient",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6c.3",
    examStrategy: 3,
    examStrategyNotes:
      "One of the frequencies we are asked to remember is the commonly used is the 10.7MHz IF used in radio receivers for FM etc. There are harmonics of 3.5MHz that fall in the IF range.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q43",
    question:
      "What safety consideration must be followed when making a mains supply filter?",
    options: [
      "That the laminated core of the choke is connected to earth",
      "That all of the components are specifically rated for mains use",
      "That Voltage Dependent Resistors (VDR) are fitted between the live and the neutral",
      "That the capacitors are rated for a working voltage of more than 250Volts DC",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6d.2",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q44",
    question:
      "You are operating your station on 14.25MHz with an ERP of 225W and measure the RF field strength 25m from your antenna as 4.2V / m. You repeat the measurement, still with an ERP of 225W, at 28.5MHz what should the second measurement be?",
    options: ["8.4V/m", "2.9V/m", "4.2V/m", "2.1V/m"],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6e.1",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q45",
    question:
      "A quarter wave vertical antenna installed without an RF earth and connected to a transmitter is likely to cause?",
    options: [
      "Excessive noise on receive, resulting in an inability to receive weaker signals",
      "RF currents in the mains earth and power leads",
      "Difficulty in getting a low SWR on the feeder to the antenna",
      "Frequency instability due to RF getting into other sections of the transmitter circuitry",
    ],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6e.2",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q46",
    question: "Advice for radio amateurs on mobile installations is in the:",
    options: [
      "Ofcom's UK Code of Practice for the installation of mobile radio and related ancillary equipment in land-based vehicles",
      "Post Office Communication Services UK Code of Practice for the installation of mobile radio and related ancillary equipment in land-based vehicles",
      "Federation of Communication Services UK Code of Practice for the installation of mobile radio and related ancillary equipment in aircraft",
      "Federation of Communication Services UK Code of Practice for the installation of mobile radio and related ancillary equipment in land-based vehicles",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) 95 of the Full Licence text book",
    syllabus: "6f.1",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q47",
    question: "The first action in dealing with an EMC complaint should be to:",
    options: [
      "cease all amateur radio activity until the problem is resolved",
      "carry out test transmissions on all bands at maximum power",
      "seek details of times and days that the problem occurs",
      "complete a report form and send it to the local office of Ofcom",
    ],
    correct: 2,
    explanation:
      "Start keeping a log if you aren't already. Check full manual where 'If a complaint is raised' and 'how a complaint is dealt with' can be found.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "6g.1",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q48",
    question: "Operating 'split' frequency is:",
    options: [
      "listening on a frequency a few kHz away from the transmit frequency",
      "listening in a different band to the one used for transmitting",
      "operating simultaneous two-way communication in the same band",
      "operating simultaneous two-way communication in different bands",
    ],
    correct: 0,
    explanation: "",
    lookup: "See page(s) 11 of the Full Licence text book",
    syllabus: "7a.1",
    week: "1",
    examStrategy: 1,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q49",
    question: "One of the 5MHz sub-bands is 10kHz wide. This will allow:",
    options: [
      "FM signals with 3kHz audio and 3kHz deviation",
      "a transmitted power of 200W provided it is centred within the sub-band",
      "up to three SSB transmissions within the sub-band",
      "AM to be transmitted with up to 5kHz of audio signal",
    ],
    correct: 2,
    explanation:
      "For FM, bandwidth needed is given by Carson's rule. So bandwidth = 2 x (max audio frequency + peak deviation) so not FM. For the 200W, see the 5MHz band plan and Licence Notes give 100W max. It is possible to fit 3 SSB transmissions within 10kHz, including spacing. For AM, the bandwidth is approx twice the audio frequency, which might just fit, but looking at the band plan, Note 3 indicates AM max bandwidth of 6kHz.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "7b.1",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q50",
    question: "If working on live equipment, you should:",
    options: [
      "be isolated from earth by a rubber mat or other insulation",
      "hold an earth lead firmly in your hand",
      "ensure that no interference is being caused to other stations by maintaining a headphone watch",
      "ensure there is a good earth connection to your body",
    ],
    correct: 0,
    explanation:
      "You do not want to be the path to ground, so being isolated is the best thing.",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8a.6",
    examStrategy: 3,
    examStrategyNotes:
      "Do nothing to encourage that electric current to flow across your chest and down to ground.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q51",
    question:
      "You have finished operating at the end of the day and you are aware that there is a strong possibility of thunderstorms. You should: ",
    options: [
      "disconnect the antenna from the antenna socket but leave it resting against the chassis of the radio",
      "remember that a neighbour’s house was recently struck by lightning and that lightning does not strike twice",
      "leave the antenna and radio connected as it is a mains operated set and has an earth lead",
      "disconnect the equipment from the mains and the antenna",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8e.1",
    examStrategy: 1,
    examStrategyNotes: "Obvious!",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q52",
    question:
      "What important action or check has not been performed in planning this outdoor operating trip? <br><br><img src='images/rsgb-full-1-q52.png' alt='test'  >",
    options: [
      "Provision of RCBOs",
      "Correct fusing",
      "Site survey",
      "Adequacy of local mains supply",
    ],
    correct: 2,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8f.4",
    examStrategy: 1,
    examStrategyNotes: "Drill...",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q53",
    question:
      "When operating outdoors with power from an electrical generator the fire extinguisher should be stored:",
    options: [
      "with the fuel store to minimise carrying in an emergency",
      "inside the operating tent to protect from rain and excessive cold",
      "alongside the generator for speed of access in the event of a fire",
      "where they are clearly visible and not alongside the generator or fuel store",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "8f.7",
    examStrategy: 1,
    examStrategyNotes: "Obvious.",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q54",
    question:
      "The purpose of the resistors shown is to provide a number of: <br><br><img src='images/rsgb-full-1-q54.png' alt='test'  >",
    options: [
      "AC voltage ranges",
      "AC current ranges",
      "DC voltage ranges",
      "DC current ranges",
    ],
    correct: 2,
    explanation: `Why the answer is "DC voltage ranges":
The circuit shows a basic moving-coil meter with selectable series resistors. Understanding this requires grasping a few key principles:

The meter movement itself is fundamentally a current-measuring device - the coil deflects fully at one specific current value (say, 1mA for full scale).
Adding a large resistor in series converts it to a voltmeter - the resistor and meter form a voltage divider. The applied voltage determines the current through the series chain, so the meter deflection becomes proportional to voltage.
Different resistor values create different voltage ranges - a 10kΩ resistor might give 0-10V range, while a 100kΩ resistor gives 0-100V range, etc.
This is a DC meter only - there's no rectification circuitry visible. A moving-coil meter cannot follow AC (it would just vibrate at 50Hz), so it measures DC only.

Note: While these resistors could theoretically provide DC current ranges if some positions used very low resistance values, the circuit as shown displays three similar resistors suggesting voltage range selection. Ammeter ranges typically require shunt resistors in parallel with the meter for higher currents, not just series resistors. Just reading this through... The resistor we select to be in series should be accurate because in the meter we need to know how the voltage is being divided to calibrate the meter reading, and to control the current (the same level of current is flowing through big and small R)

Absolutely! You've just identified something really important that I should have emphasized more clearly!

The resistor values need to be precise and stable because:

Calibration depends on it: If you select the "100V range" resistor, the meter scale is marked assuming that specific resistance value. If the resistor is off by 10%, all your voltage readings will be wrong by 10%!
The voltage division ratio must be exact: When you apply, say, 50V to the combination and want the needle to point to "50" on the scale, you need to know precisely how much current will flow: I = V / (R_series + R_meter). If R_series isn't what you think it is, the calibration is meaningless.
Temperature stability matters too: These are often precision metal-film or wirewound resistors because regular carbon resistors can change resistance with temperature, throwing off your calibration.
And you're right about the current being the same through both! That's the series connection - the same current must flow through the big resistor and the meter. The big resistor "drops" most of the voltage, the meter drops a tiny bit, but they both carry identical current.

This is why quality multimeters use precision resistors (often 1% or better tolerance) for their range selection - it's not just about having "some resistance," it's about having exactly the right, known resistance to make the calibration accurate.`,
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.1",
    examStrategy: 3,
    examStrategyNotes:
      "The coil will defelct on a given current, so we need a range of voltage dividers",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q55",
    question:
      "To measure the RF output power of a transmitter, the power meter should be:",
    options: [
      "connected in parallel with the antenna",
      "connected in between the transmitter and its power supply",
      "connected as close as possible to the antenna",
      "set to the highest power range to begin with",
    ],
    correct: 3,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.5",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q56",
    question:
      "An oscilloscope is displaying an AC signal showing 1 cycle across 5 divisions on the x-axis of the screen. The time base is set to 5μs per division.What is the frequency of the AC signal?",
    options: ["40kHz", "2kHz", "400kHz", "200kHz"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9a.8",
    examStrategy: 2,
    examStrategyNotes:
      "First get the Period, then Frequency is the reciprocal!",
    examCalculation: 2,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q57",
    question:
      "The dBm is often used to express power with respect to 1mW; that is 0dBm = 1mW. What power is 20dBm?",
    options: ["10mW", "100mW", "1mW", "1000mW"],
    correct: 1,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9b.1",
    examStrategy: 1,
    examStrategyNotes: "More Learning Materials: Claude?",
    examCalculation: 0,
    exam_NOT: false,
  },
  {
    source: "RSGB Full Mock 1 Q58",
    question:
      "A home-made transmitter uses a crystal at 3.5MHz multiplied up to 28MHz. The crystal is specified as 0.5 ppm per degree C. At switch on the room is at 18C but inside the transmitter case is 36C when warmed up. By how much will the transmitted frequency vary in that time?",
    options: ["252Hz", "32Hz", "504Hz", "63Hz"],
    correct: 0,
    explanation: "",
    lookup: "See page(s) x of the Full Licence text book",
    syllabus: "9c.1",
    examStrategy: 3,
    examStrategyNotes:
      "The crystal variation id 0.5 x 18 all over 1 million, then multiply that by 28MHz, the millions cancel out and we are left with 9 * 28 Hz. Best to use a calculator on the last easy calc!",
    examCalculation: 2,
    exam_NOT: false,
  },
]

export default RSGB_FULL_MOCK_1
