import EXAM_SECRETS_QUESTIONS from "./EXAM_SECRETS_QUESTIONS.js"
import EXAM_SECRETS_FULL_PAPER from "./EXAM_SECRETS_FULL_PAPER.js"
import RSGB_FULL_MOCK_1 from "./RSGB_FULL_MOCK_1.js"
import RSGB_FULL_MOCK_2 from "./RSGB_FULL_MOCK_2.js"
import RSGB_FULL_MOCK_3 from "./RSGB_FULL_MOCK_3.js"
import RSGB_DIRECT_FULL_MOCKS from "./RSGB_DIRECT_FULL_MOCKS.js"
import BBDL_FULL_QUIZZES from "./BBDL_FULL_QUIZZES.js"
import OWN_QUESTIONS from "./OWN_QUESTIONS.js"
// import CLAUDE_QUIZ from "./CLAUDE_QUIZ.js"

const W99quiz = [
  ...RSGB_FULL_MOCK_1,
  ...RSGB_FULL_MOCK_2,
  ...RSGB_FULL_MOCK_3,
  ...RSGB_DIRECT_FULL_MOCKS,
  ...EXAM_SECRETS_QUESTIONS,
  ...EXAM_SECRETS_FULL_PAPER,
  ...BBDL_FULL_QUIZZES,
  ...OWN_QUESTIONS,
  // ...CLAUDE_QUIZ
]

export default W99quiz

// experimental
export {
  RSGB_FULL_MOCK_1,
  RSGB_FULL_MOCK_2,
  RSGB_FULL_MOCK_3,
  EXAM_SECRETS_FULL_PAPER,
  RSGB_DIRECT_FULL_MOCKS,
}
